// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         domainName: "domainName",
 *         emailBox: "emailBox"
 *     }
 */
export interface DeleteEmailForwardingRequest {
    /** DomainName is the domain to delete the email forwarded box from. */
    domainName: string;
    /** EmailBox is which email box to delete. */
    emailBox: string;
}
