// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         domainName: "domainName",
 *         emailBox: "emailBox"
 *     }
 */
export interface EmailForwardingsUpdateEmailForwardingBody {
    /** DomainName is the domain part of the email address to forward. */
    domainName: string;
    /** EmailBox is the user portion of the email address to forward. */
    emailBox: string;
    /** EmailTo is the entire email address to forward email to. */
    emailTo?: string;
}
