// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         domainName: "domainName",
 *         perPage: 100,
 *         page: 1
 *     }
 */
export interface ListEmailForwardingsRequest {
    /** DomainName is the domain to list email forwarded boxes for. */
    domainName: string;
    /** (optional) Per Page is the number of records to return per request. Per Page defaults to 500 if not set. */
    perPage?: number;
    /** (optional) Page is which page to return. Default to page 1 if not set. */
    page?: number;
}
