// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../core/index.js";
import * as errors from "../../errors/index.js";
import type * as Namecom from "../index.js";

export class LockedError extends errors.NamecomError {
    public declare readonly body: Namecom.Locked423;

    constructor(body: Namecom.Locked423, rawResponse?: core.RawResponse) {
        super({
            message: "LockedError",
            statusCode: 423,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, new.target.prototype);
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, this.constructor);
        }

        this.name = "LockedError";
    }
}
