// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "X-Idempotency-Key": "083910ef-04e4-4bd1-a0bf-3737fe005ca8",
 *         orderId: 123456,
 *         orderItemIds: [987654]
 *     }
 *
 * @example
 *     {
 *         "X-Idempotency-Key": "083910ef-04e4-4bd1-a0bf-3737fe005ca8",
 *         orderId: 123456,
 *         orderItemIds: [987654, 987655]
 *     }
 */
export interface RefundRequest {
    /** A unique string (e.g., a UUID v4) to make the request idempotent. This key ensures that if the request is retried, the operation will not be performed multiple times. Subsequent requests with the same key will return the original result. Idempotency keys are valid for 12 hours. */
    "X-Idempotency-Key"?: string;
    /** The unique identifier of the order containing the item(s) to be refunded. Use the List Orders endpoint to retrieve order IDs. */
    orderId: number;
    /** An array of order item IDs to be refunded. All items must belong to the specified order. Use the List Orders endpoint to retrieve order item IDs. */
    orderItemIds: number[];
}
