// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Namecom from "../../../index.js";

export declare namespace RefundsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Use the Refunds endpoint to delete eligible domains and advanced security products during the Add Grace Period (AGP) and automatically issue refunds for the associated order items. You can use the List Orders endpoint to retrieve order IDs, then pass those IDs into the Refunds endpoint to process eligible deletions and refunds.   This endpoint enforces AGP delete limits and supports only domain registrations and advanced security add-ons. Refunds are issued  to the original payment method on file. If the original payment method is unavailable, the refund will be credited to the account balance.
 */
export class RefundsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<RefundsClient.Options>;

    constructor(options: RefundsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Deletes eligible domains and security products during the Add Grace Period (AGP) and automatically issues refunds for the associated order items.
     *
     * ### Eligibility Requirements
     *
     * - **Product Types**: Only `registration` and `whois_privacy` product types are eligible for refunds.
     * - **AGP Timing**: Items must be within the Add Grace Period (typically 5 days from registration, varies by TLD).
     * - **Order Ownership**: All `orderItemIds` must belong to the specified `orderId`.
     *
     * ### Refund Processing
     *
     * Refunds are processed in the following order:
     * 1. Domain deletion is attempted for each eligible order item
     * 2. Upon successful deletion, the refund is issued
     * 3. Refunds are sent to the original payment method on file
     * 4. If the original payment method is unavailable, the refund is credited to the account balance
     *
     * ### Idempotency
     *
     * This endpoint supports idempotent requests via the `X-Idempotency-Key` header. If you retry a request with the same idempotency key, you will receive the same response as the original request. This is useful for safely retrying requests without risk of processing duplicate refunds.
     *
     * @param {Namecom.RefundRequest} request
     * @param {RefundsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Namecom.BadRequestError}
     * @throws {@link Namecom.UnauthorizedError}
     * @throws {@link Namecom.ForbiddenError}
     * @throws {@link Namecom.NotFoundError}
     * @throws {@link Namecom.MethodNotAllowedError}
     * @throws {@link Namecom.ConflictError}
     * @throws {@link Namecom.UnsupportedMediaTypeError}
     * @throws {@link Namecom.LockedError}
     * @throws {@link Namecom.TooManyRequestsError}
     * @throws {@link Namecom.InternalServerError}
     * @throws {@link Namecom.BadGatewayError}
     * @throws {@link Namecom.GatewayTimeoutError}
     *
     * @example
     *     await client.refunds.processRefund({
     *         "X-Idempotency-Key": "083910ef-04e4-4bd1-a0bf-3737fe005ca8",
     *         orderId: 123456,
     *         orderItemIds: [987654]
     *     })
     *
     * @example
     *     await client.refunds.processRefund({
     *         "X-Idempotency-Key": "083910ef-04e4-4bd1-a0bf-3737fe005ca8",
     *         orderId: 123456,
     *         orderItemIds: [987654, 987655]
     *     })
     */
    public processRefund(
        request: Namecom.RefundRequest,
        requestOptions?: RefundsClient.RequestOptions,
    ): core.HttpResponsePromise<Namecom.RefundResponse> {
        return core.HttpResponsePromise.fromPromise(this.__processRefund(request, requestOptions));
    }

    private async __processRefund(
        request: Namecom.RefundRequest,
        requestOptions?: RefundsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Namecom.RefundResponse>> {
        const { "X-Idempotency-Key": idempotencyKey, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Idempotency-Key": idempotencyKey }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NamecomEnvironment.Sandbox,
                "core/v1/refund",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Namecom.RefundResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Namecom.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Namecom.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Namecom.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Namecom.NotFoundError(_response.error.body as Namecom.NotFound404, _response.rawResponse);
                case 405:
                    throw new Namecom.MethodNotAllowedError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new Namecom.ConflictError(_response.error.body as unknown, _response.rawResponse);
                case 415:
                    throw new Namecom.UnsupportedMediaTypeError(
                        _response.error.body as Namecom.UnsupportedMedia415,
                        _response.rawResponse,
                    );
                case 423:
                    throw new Namecom.LockedError(_response.error.body as Namecom.Locked423, _response.rawResponse);
                case 429:
                    throw new Namecom.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Namecom.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 502:
                    throw new Namecom.BadGatewayError(_response.error.body as unknown, _response.rawResponse);
                case 504:
                    throw new Namecom.GatewayTimeoutError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.NamecomError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/core/v1/refund");
    }
}
