// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         domainName: "domainName",
 *         id: 1
 *     }
 */
export interface DeleteRecordRequest {
    /** DomainName is the zone that the record to be deleted exists in. */
    domainName: string;
    /** ID is the server-assigned unique identifier for the Record to be deleted. If the Record with that ID does not exist in the specified Domain, an error is returned. */
    id: number;
}
