// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         domainName: "domainName",
 *         id: 1
 *     }
 */
export interface GetRecordRequest {
    /** DomainName is the zone the record exists in. */
    domainName: string;
    /** ID is the server-assigned unique identifier for this record. */
    id: number;
}
