// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         domain: "tiktok.page"
 *     }
 */
export interface DomainClaimsCheckRequest {
    /** The domain name to check for trademark claims (e.g., 'tiktok.page', 'example.com'). Include the full domain name including the TLD. */
    domain: string;
    /** The type of purchase/registration for which to check claims. Defaults to 'registration'. Other values like 'landrush_eap', 'landrush_auction_a', 'landrush_reserve_a' may be used during new gTLD launches. */
    purchaseType?: DomainClaimsCheckRequest.PurchaseType;
}

export namespace DomainClaimsCheckRequest {
    /** The type of purchase/registration for which to check claims. Defaults to 'registration'. Other values like 'landrush_eap', 'landrush_auction_a', 'landrush_reserve_a' may be used during new gTLD launches. */
    export const PurchaseType = {
        Registration: "registration",
        LandrushEap: "landrush_eap",
        LandrushAuctionA: "landrush_auction_a",
        LandrushReserveA: "landrush_reserve_a",
    } as const;
    export type PurchaseType = (typeof PurchaseType)[keyof typeof PurchaseType];
}
