// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         domainName: "example.com",
 *         hostname: "ns1.example.com"
 *     }
 */
export interface GetVanityNameserverRequest {
    /** The domain name associated with the vanity nameserver. */
    domainName: string;
    /** The hostname of the vanity nameserver to retrieve. */
    hostname: string;
}
