// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         domainName: "example.com",
 *         perPage: 50,
 *         page: 2
 *     }
 */
export interface ListVanityNameserversRequest {
    /** The domain name to list vanity nameservers for. */
    domainName: string;
    /** The number of records to return per page. Defaults to 500. */
    perPage?: number;
    /** The page number to return. */
    page?: number;
}
