// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         domainName: "example.com",
 *         hostname: "ns1.example.com",
 *         ips: ["192.168.1.10", "2001:0db8:85a3:0000:0000:8a2e:0370:7334"]
 *     }
 */
export interface UpdateVanityNameserverBody {
    /** The domain name associated with the vanity nameserver. */
    domainName: string;
    /** The hostname of the vanity nameserver to update. */
    hostname: string;
    /** IPs is the updated list of IP addresses to be used for glue records for this vanity nameserver. Providing an empty array will remove all existing IPs. */
    ips: string[];
}
