// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../../../../index.js";

/**
 * @example
 *     {
 *         domainName: "domainName",
 *         body: {}
 *     }
 */
export interface CancelTransferRequest {
    /** DomainName is the domain to cancel the transfer for. */
    domainName: string;
    body: Namecom.EmptyObject;
}
