// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         domainName: "domainName"
 *     }
 */
export interface CancelTransferRequest {
    /** DomainName is the domain to cancel the transfer for. */
    domainName: string;
}
