// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../../../../index.js";

/**
 * @example
 *     {
 *         domainName: "example.com",
 *         authCode: "ABC123"
 *     }
 */
export interface CreateInternalTransferInRequest {
    /** Fully qualified domain name to transfer in. The domain must be registered in another name.com account (the losing account). */
    domainName: string;
    /** Transfer authorization code (EPP/auth code) for the domain. The losing account holder must obtain this code from the [name.com](https://www.name.com) dashboard; it is not exposed by this API for the losing account. */
    authCode: string;
    /** WHOIS contacts to apply after the transfer. If omitted, the gaining account's default contacts are applied. If provided, include any roles to override; omitted roles use the gaining account's default contacts. Each supplied role must include complete contact fields. A registrar contact-change transfer lock may apply according to the gaining account's settings, consistent with the Set Contacts endpoint. */
    contacts?: Namecom.ContactsRequest;
}
