// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         authCode: "ABC123",
 *         domainName: "example.com"
 *     }
 */
export interface CreateTransferRequest {
    /** AuthCode is the authorization code for the transfer. Not all TLDs require authorization codes, but most do. */
    authCode: string;
    /** DomainName is the domain you want to transfer to name.com. */
    domainName: string;
    /** PrivacyEnabled is a flag on whether to purchase Whois Privacy with the transfer. If this flag is omitted from the request, the system will check the account's Whois Privacy auto-add settings. If auto-add is enabled in your account settings, Whois Privacy will be added by default, provided the TLD supports it. */
    privacyEnabled?: boolean;
    /** PurchasePrice is the USD inbound transfer fee, before VAT. VAT is applied when applicable and must not be included here. If sent, must match Get Pricing `transferPrice` exactly or the request will fail.. **Omit** for standard (non-premium) transfers. **Required** for premium transfers — use `transferPrice` from [Get Pricing](/api/v1/reference/domains/get-pricing-for-domain). */
    purchasePrice?: number;
}
