// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         authCode: "ABC123",
 *         domainName: "example.com"
 *     }
 */
export interface CreateTransferRequest {
    /** AuthCode is the authorization code for the transfer. Not all TLDs require authorization codes, but most do. */
    authCode: string;
    /** DomainName is the domain you want to transfer to name.com. */
    domainName: string;
    /** Whether to include Whois Privacy with the transfer. Whois Privacy is free. If omitted, the account default from account settings is used. Privacy is only added when the TLD supports it. */
    privacyEnabled?: boolean;
    /** PurchasePrice is the USD inbound transfer fee, before VAT. VAT is applied when applicable and must not be included here. If sent, must match Get Pricing `transferPrice` exactly or the request will fail.. **Omit** for standard (non-premium) transfers. **Required** for premium transfers — use `transferPrice` from [Get Pricing](/api/v1/reference/domains/get-pricing-for-domain). */
    purchasePrice?: number;
}
