// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         domainName: "domainName"
 *     }
 */
export interface GetTransferEligibilityRequest {
    /** The domain to check transfer eligibility for. Punycode is normalized server-side, so either ASCII or UTF-8 is accepted. */
    domainName: string;
}
