// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListTransfersRequest {
    /** Per Page is the number of records to return per request. Per Page defaults to 500. */
    perPage?: number;
    /** Page is which page to return. */
    page?: number;
}
