// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../index.js";

/**
 * Account lists all the data for an account. This schema is used for requests.
 */
export interface AccountRequest {
    /** Contact information associated with this account. */
    contacts?: Namecom.ContactsRequest | undefined;
    /** AccountId is the unique id of account. */
    accountId?: number | undefined;
    /** AccountName is the unique name of the account.  Minimum length is 6 characters, maximum length is 60. */
    accountName?: string | undefined;
    /** When set to true, domains in this account will be automatically renewed before expiration. */
    autoRenew?: boolean | undefined;
    /** CreateDate is the date the account was created. */
    createDate?: string | undefined;
    /** Password has minimum length of 7 characters. It must contain at least 1 letter and at least 1 number/symbol. */
    password?: string | undefined;
}
