// This file was auto-generated by Fern from our API Definition.

export interface BadGatewayErrorBody {
    /** A human-readable message providing more details about the error. */
    message: string;
}
