// This file was auto-generated by Fern from our API Definition.

/**
 * Response after successfully canceling a domain transfer out request.
 */
export interface CancelTransferOutResponse {
    /** The punycode-encoded domain name. */
    domainName: string;
    /** The transfer-out status after the operation (e.g. canceled when the cancel succeeded). */
    status: CancelTransferOutResponse.Status;
}

export namespace CancelTransferOutResponse {
    /** The transfer-out status after the operation (e.g. canceled when the cancel succeeded). */
    export const Status = {
        Canceled: "canceled",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
