// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../index.js";

export type ContactVerificationStatusChangeVerification =
    | Namecom.ContactVerificationStatusChangeVerification.Verified
    | Namecom.ContactVerificationStatusChangeVerification.Unverified;

export namespace ContactVerificationStatusChangeVerification {
    export interface Verified {
        status: "verified";
    }

    export interface Unverified {
        status: "unverified";
        /** The date when the contact should be verified by. */
        verifyBy: string;
    }
}
