// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../index.js";

export interface ContactVerificationStatusChange {
    eventName: ContactVerificationStatusChange.EventName;
    domains: string[];
    /** The id of the verification record for the contact. Please note, this is different than the `contact_id` that may be returned in other API contexts. This id specifically relates to the verification and will be different than an `contact_id` for the same contact record in other contexts. */
    verificationId: number;
    verification: Namecom.ContactVerificationStatusChangeVerification;
}

export namespace ContactVerificationStatusChange {
    export const EventName = {
        ContactVerificationStatusChange: "contact.verification.status_change",
    } as const;
    export type EventName = (typeof EventName)[keyof typeof EventName];
}
