// This file was auto-generated by Fern from our API Definition.

/**
 * Response for resending a contact verification email.
 */
export interface ContactVerificationResendResponse {
    /** Whether a verification email was sent as a result of this request. */
    sent: boolean;
    /** The verificationId for the contact verification record. */
    verificationId: number;
    /** When the client can attempt to resend again, as an RFC3339/ISO-8601 UTC timestamp. This field is always returned, including when throttling applies. */
    nextEligibleAt: string;
}
