// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../index.js";

/**
 * Contacts stores the contact information for the roles related to domains.
 */
export interface Contacts {
    admin?: Namecom.Contact | undefined;
    billing?: Namecom.Contact | undefined;
    registrant?: Namecom.RegistrantContact | undefined;
    tech?: Namecom.Contact | undefined;
}
