// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../index.js";

/**
 * ContactsRequirement defines the registration requirements for contact fields for a specific TLD, including required fields, validation rules, and conditional logic. This follows the RequirementField structure with contact roles as nested fields.
 */
export interface ContactsRequirement {
    /** A detailed description of the contact requirements for this TLD, including eligibility criteria, restrictions, and important notes. */
    description?: string | undefined;
    /** The requirement type, which will be "string" for contacts. */
    type: string;
    /** Whether contact information is mandatory for domain registration. */
    required: ContactsRequirement.Required;
    /** A user-friendly label for the contacts field. */
    label?: string | undefined;
    /** An object containing contact roles (registrant, tech, admin, etc.) with their individual field requirements. */
    fields?: Record<string, ContactsRequirement.Fields.Value> | undefined;
}

export namespace ContactsRequirement {
    /**
     * Whether contact information is mandatory for domain registration.
     */
    export type Required = boolean | string;

    export namespace Fields {
        /**
         * Contact role requirements (e.g., registrant, tech, admin)
         */
        export interface Value {
            /** Description of the contact role requirements. */
            description?: string | undefined;
            /** The requirement type for this contact role. */
            type?: string | undefined;
            /** Whether this contact role is required. */
            required?: Value.Required | undefined;
            /** Individual contact fields for this role, following RequirementField structure. */
            fields?: Record<string, Namecom.RequirementField> | undefined;
        }

        export namespace Value {
            /**
             * Whether this contact role is required.
             */
            export type Required = boolean | string;
        }
    }
}
