// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../index.js";

/**
 * Contacts stores the contact information for the roles related to domains. This schema is used for requests.
 */
export interface ContactsRequest {
    admin?: Namecom.ContactRequest | undefined;
    billing?: Namecom.ContactRequest | undefined;
    registrant?: Namecom.RegistrantContactRequest | undefined;
    tech?: Namecom.ContactRequest | undefined;
}
