// This file was auto-generated by Fern from our API Definition.

/**
 * CreateAccountResponse contains information about the newly created account and the API credentials generated for it.
 */
export interface CreateAccountResponse {
    /** AccountName is the unique user-assigned name of newly created account. */
    accountName: string;
    /** The authentication token that should be used to access the API. This value is only returned once upon account creation. */
    apiToken: string;
    /** ApiTokenName user assigned name of api token. */
    apiTokenName: string;
}
