// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../index.js";

/**
 * CreateDomainResponse contains the domain info as well as the order info for the created domain.
 */
export interface CreateDomainResponse {
    domain: Namecom.DomainResponsePayload;
    /** Order is an identifier for this purchase. */
    order: number;
    /** TotalPaid is the total amount paid, including VAT and Whois privacy protection. */
    totalPaid: number;
}
