// This file was auto-generated by Fern from our API Definition.

/**
 * DNSSEC contains all the data required to create a DS record at the registry.
 */
export interface Dnssec {
    algorithm: number;
    /** Digest is a digest of the DNSKEY RR that is registered with the registry. */
    digest: string;
    digestType: number;
    /** DomainName is the domain name. */
    domainName: string;
    keyTag: number;
}
