// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../index.js";

/**
 * Response containing domain-specific claims data and trademark information
 */
export interface DomainClaimsCheckResponse {
    /** The domain name that was checked for claims */
    domain: string;
    /** List of trademark claims found against this domain */
    claims: Namecom.TrademarkClaim[];
    /** Whether the TLD of this domain requires claims checking */
    claimsProcessActive?: boolean | undefined;
    /** The claim identifier from TMCH (null if no claims found) */
    claimId?: (string | null) | undefined;
    /** The date before which the claim acknowledgment is not valid (null if no claims found) */
    notBefore?: (string | null) | undefined;
    /** The date after which the claim acknowledgment expires (null if no claims found) */
    notAfter?: (string | null) | undefined;
    /** Markdown content to display about this specific trademark claim */
    claimsNotice?: string | undefined;
}
