// This file was auto-generated by Fern from our API Definition.

/**
 * Payload for `domain.transfer_out.status_change`. `completed` means the domain left name.com. `canceled` means the outbound transfer is no longer pending at the registry.
 */
export interface DomainTransferOutStatusChange {
    /** The name of the subscription event. */
    eventName: DomainTransferOutStatusChange.EventName;
    /** The domain whose outbound transfer status changed. For `completed`, the domain has left name.com; for `initiated` and `canceled`, it remains on the losing account. */
    domainName: string;
    /** `initiated` (pending out started), `completed` (domain removed), or `canceled` (no longer pending at the registry). */
    status: DomainTransferOutStatusChange.Status;
    /** The registry client ID associated with the domain at the time of transfer out, when available. This can help identify the gaining registrar at the registry. */
    registryClientId?: (string | null) | undefined;
}

export namespace DomainTransferOutStatusChange {
    /** The name of the subscription event. */
    export const EventName = {
        DomainTransferOutStatusChange: "domain.transfer_out.status_change",
    } as const;
    export type EventName = (typeof EventName)[keyof typeof EventName];
    /** `initiated` (pending out started), `completed` (domain removed), or `canceled` (no longer pending at the registry). */
    export const Status = {
        Initiated: "initiated",
        Completed: "completed",
        Canceled: "canceled",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
