// This file was auto-generated by Fern from our API Definition.

/**
 * Claims acknowledgement data is required if trademark claims exist for requested domain. This data is obtained from a [Domain Claims Check](/api/v1/reference/domain-info/check-domain-claims) response and includes the claim identifier and validity dates.
 */
export interface DomainClaimsInfo {
    /** The claim identifier from TMCH (Trademark Clearinghouse) */
    claimId?: string | undefined;
    /** The date before which the claim acknowledgment is not valid */
    notBefore?: string | undefined;
    /** The date after which the claim acknowledgment expires */
    notAfter?: string | undefined;
}
