// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../index.js";

/**
 * The payload to be sent for when making a request to purchase a domain.
 */
export interface DomainCreatePayload {
    contacts?: Namecom.ContactsRequest | undefined;
    /** The punycode-encoded value of the domain name. */
    domainName?: string | undefined;
    /** The date and time when the domain was created at the registry. */
    createDate?: string | undefined;
    /** The date and time when the domain will expire. */
    expireDate?: string | undefined;
    /** Indicates whether the domain is set to renew automatically before expiration. */
    autorenewEnabled?: boolean | undefined;
    /** Indicates if the domain is **transfer locked**, preventing transfers to another registrar. */
    locked?: boolean | undefined;
    /** List of all registry locking statuses currently applied to the domain. Use this to see which locks are active (e.g. clientTransferProhibited, clientHold). Empty when the domain has no locks applied. */
    locks?: string[] | undefined;
    /** When present, the domain has an active ICANN-mandated transfer lock (new registration, transfer-in, or material registrant contact change) that blocks client unlock via the API until this time. When omitted, there is no active policy transfer lock with a known expiry — the domain may still be locked (`locked: true`) due to a voluntary user lock. Does not represent RegistrarLock, AccountLock, verification holds, trademark-claim locks, or admin TransferLock with no expiry date. */
    transferLockExpiresAt?: string | undefined;
    /** Indicates if Whois Privacy is enabled for this domain. */
    privacyEnabled?: boolean | undefined;
    /** The list of nameservers assigned to this domain. If unspecified, it defaults to the account's default nameservers. */
    nameservers?: string[] | undefined;
    /** The cost to renew the domain. This may be required for the RenewDomain operation. */
    renewalPrice?: number | undefined;
}
