// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../index.js";

/**
 * The response format for a domain.
 */
export interface DomainResponsePayload {
    domainName: Namecom.DomainName;
    createDate?: Namecom.CreateDate | undefined;
    expireDate?: Namecom.ExpireDate | undefined;
    autorenewEnabled: Namecom.AutorenewEnabled;
    locked: Namecom.Locked;
    transferLockExpiresAt?: Namecom.TransferLockExpiresAt | undefined;
    privacyEnabled: Namecom.PrivacyEnabled;
    nameservers: Namecom.Nameservers;
    renewalPrice?: Namecom.RenewalPrice | undefined;
    /** List of all registry locking statuses currently applied to the domain. Use this to see which locks are active (e.g. clientTransferProhibited, clientHold). Empty when the domain has no locks applied. */
    locks?: string[] | undefined;
    contacts?: Namecom.Contacts | undefined;
}
