// This file was auto-generated by Fern from our API Definition.

/**
 * Payload sent when a registry reports that a domain must remediate a policy compliance issue before a deadline. By default, name.com emails the registrant; subscribing replaces that email so you can notify the end user from these fields. If you have signed an addendum to assume all email responsibility, name.com does not send the email and this webhook is the only delivery path. Whitelabeled branding is applied to the email when your account has it configured.
 */
export interface DomainRegistryComplianceNotice {
    /** The name of the subscription event. */
    eventName: DomainRegistryComplianceNotice.EventName;
    /** The domain subject to the registry compliance notice. */
    domainName: string;
    /** Stable, namespaced identifier for the registry policy requiring remediation. Branch on this value rather than any human-readable field. */
    policy: DomainRegistryComplianceNotice.Policy;
    /** Human-readable name of the registration policy associated with the compliance requirement. */
    policyName: string;
    /** URL of the registration policy associated with the compliance requirement. */
    policyUrl: string;
    /** Human-readable name of the registry that issued the compliance notice. */
    registryName: string;
    /** Registry mailbox for evidence and questions, when the registry publishes one. Include it in the message body when notifying the registrant. Omitted when the registry does not publish a contact address. */
    registryEmail?: string | undefined;
    /** RFC 5322 Message-ID of the registry's original notice, when available. Omitted when the registry notice had no Message-ID. */
    originalMessageId?: string | undefined;
    /** Human-readable explanation of the compliance issue identified by the registry. Suitable for forwarding to the registrant. The wording may change; do not branch on this text. */
    issueDescription: string;
    /** Human-readable instructions for resolving the compliance issue. Suitable for forwarding to the registrant. The wording may change; do not branch on this text. */
    remediationInstructions: string;
    /** Human-readable reminder that the registrant agreed to the applicable registration policy. Suitable for forwarding to the registrant. The wording may change; do not branch on this text. */
    agreementReminder: string;
    /** Human-readable explanation of what the registry may do if the issue is not remediated by `complianceDeadline`. Suitable for forwarding to the registrant. */
    noncomplianceConsequences: string;
    /** Human-readable instruction for the registrant to contact the registry (not the registrar) if they believe the domain is compliant or need to submit evidence. Suitable for forwarding. */
    contactInstructions: string;
    /** The deadline by which the compliance issue must be remediated. */
    complianceDeadline: string;
    /** The remediation period supplied by the registry, in days. */
    remediationPeriodDays: number;
}

export namespace DomainRegistryComplianceNotice {
    /** The name of the subscription event. */
    export const EventName = {
        DomainRegistryComplianceNotice: "domain.registry.compliance_notice",
    } as const;
    export type EventName = (typeof EventName)[keyof typeof EventName];
    /** Stable, namespaced identifier for the registry policy requiring remediation. Branch on this value rather than any human-readable field. */
    export const Policy = {
        NewResolvesWithin100Days: "new_resolves_within_100_days",
        NewUsedForAction: "new_used_for_action",
        NewAccountForReview: "new_account_for_review",
    } as const;
    export type Policy = (typeof Policy)[keyof typeof Policy];
}
