// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../index.js";

/**
 * Payload sent when a domain transfers OUT from the webhook subscriber's account to another name.com account.
 */
export interface DomainTransferInternalOutStatusChange {
    /** The name of the subscription event. */
    eventName: DomainTransferInternalOutStatusChange.EventName;
    /** The internal transfer ID for this move, when available. Omitted when no transfer ID has been assigned for the event. */
    transferId?: number | undefined;
    /** The account id that previously owned the domain (the losing account). */
    sourceAccountId: number;
    /** The account id that now owns the domain (the gaining account). */
    destinationAccountId: number;
    status: DomainTransferInternalOutStatusChange.Status;
    /** When the domain transfer out occurred. */
    occurredAt: string;
    domain: Namecom.DomainResponsePayload;
}

export namespace DomainTransferInternalOutStatusChange {
    /** The name of the subscription event. */
    export const EventName = {
        DomainTransferInternalOut: "domain.transfer.internal_out",
    } as const;
    export type EventName = (typeof EventName)[keyof typeof EventName];
    export const Status = {
        Completed: "completed",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
