// This file was auto-generated by Fern from our API Definition.

/**
 * Payload sent when a domain transfer OUT from name.com to another registrar has a status change (initiated, completed, or canceled). When status is "completed", the domain has been removed from name.com. In some edge cases (including near-expiration scenarios) the data may not be fully accurate.
 */
export interface DomainTransferOutStatusChange {
    /** The name of the subscription event. */
    eventName: DomainTransferOutStatusChange.EventName;
    /** The domain that has transferred out of name.com. */
    domainName: string;
    /** The status of the transfer out event. May be "initiated" (transfer out was started), "completed" (domain has been removed from the account), or "canceled" (transfer out was canceled before completion). */
    status: DomainTransferOutStatusChange.Status;
    /** The registry client ID associated with the domain at the time of transfer out, when available. This can help identify the gaining registrar at the registry. */
    registryClientId?: (string | null) | undefined;
}

export namespace DomainTransferOutStatusChange {
    /** The name of the subscription event. */
    export const EventName = {
        DomainTransferOutStatusChange: "domain.transfer_out.status_change",
    } as const;
    export type EventName = (typeof EventName)[keyof typeof EventName];
    /** The status of the transfer out event. May be "initiated" (transfer out was started), "completed" (domain has been removed from the account), or "canceled" (transfer out was canceled before completion). */
    export const Status = {
        Initiated: "initiated",
        Completed: "completed",
        Canceled: "canceled",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
