// This file was auto-generated by Fern from our API Definition.

/**
 * Payload sent when a domain create request fails after asynchronous registry processing. Most domain creates succeed immediately; this event covers the case where the registry initially accepts processing but later rejects or fails the registration.
 */
export interface DomainRegistryRejection {
    /** The name of the subscription event. */
    eventName: DomainRegistryRejection.EventName;
    /** The domain name that failed to register. */
    domainName: string;
    /** The unique identifier of the order for the failed domain create. Use the List Orders endpoint to retrieve order details. */
    orderId: number;
    /** The unique identifier of the order line item for the failed domain create. Use the List Orders endpoint to retrieve order item details. */
    orderItemId: number;
    /** When the asynchronous registration failure was recorded. */
    occurredAt: string;
    /** Optional human-readable or registry-provided detail about the failure, when available. */
    reason?: string | undefined;
}

export namespace DomainRegistryRejection {
    /** The name of the subscription event. */
    export const EventName = {
        DomainRegistryRejection: "domain.registry.rejection",
    } as const;
    export type EventName = (typeof EventName)[keyof typeof EventName];
}
