// This file was auto-generated by Fern from our API Definition.

export interface DomainLockStatusChange {
    eventName: DomainLockStatusChange.EventName;
    /** Fully-qualified domain name */
    domainName: string;
    action: DomainLockStatusChange.Action;
    /** The lock type affected by this event (added or removed) */
    lockType: DomainLockStatusChange.LockType;
    /** Current registry statuses after the change */
    registryStatuses: string[];
}

export namespace DomainLockStatusChange {
    export const EventName = {
        DomainLockStatusChange: "domain.lock.status_change",
    } as const;
    export type EventName = (typeof EventName)[keyof typeof EventName];
    export const Action = {
        Added: "added",
        Removed: "removed",
    } as const;
    export type Action = (typeof Action)[keyof typeof Action];
    /** The lock type affected by this event (added or removed) */
    export const LockType = {
        RegistrarLock: "RegistrarLock",
        TransferLock: "TransferLock",
        AccountLock: "AccountLock",
        ClientHold: "ClientHold",
        VerificationClientHold: "VerificationClientHold",
        VerificationHold: "VerificationHold",
        PrivacyLock: "PrivacyLock",
        ExpirationClientHold: "ExpirationClientHold",
    } as const;
    export type LockType = (typeof LockType)[keyof typeof LockType];
}
