// This file was auto-generated by Fern from our API Definition.

/**
 * Empty JSON object. This operation does not accept a payload; clients must still send `Content-Type: application/json` with body `{}`.
 */
export type EmptyObject = {};
