// This file was auto-generated by Fern from our API Definition.

export interface GenericError500 {
    /** A human-readable message providing more details about the error. */
    message: string;
    /** Additional context or information about the error. */
    details?: (string | null) | undefined;
}
