// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../index.js";

/**
 * ListURLForwardingsResponse is the response for the ListURLForwardings function.
 */
export interface ListUrlForwardingsResponse {
    /** LastPage is the identifier for the final page of results. It is only populated if there is another page of results after the current page. */
    lastPage?: (number | null) | undefined;
    /** NextPage is the identifier for the next page of results. It is only populated if there is another page of results after the current page. */
    nextPage?: (number | null) | undefined;
    /** URLForwarding is the list of URL forwarding entries. */
    urlForwarding: Namecom.UrlForwardingResponse[];
}
