// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../index.js";

/**
 * ListVanityNameserversResponse returns the list of vanity nameservers for the domain.
 */
export interface ListVanityNameserversResponse {
    /** LastPage is the identifier for the final page of results. It is only populated if there is another page of results after the current page. If no further pages exist, this field will be null. */
    lastPage?: (number | null) | undefined;
    /** NextPage is the identifier for the next page of results. It is only populated if there is another page of results after the current page. If no further pages exist, this field will be null. */
    nextPage?: (number | null) | undefined;
    /** VanityNameservers is the list of vanity nameservers associated with the domain. If no vanity nameservers are configured, this will be an empty array. */
    vanityNameservers: Namecom.VanityNameserverResponse[];
}
