// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../index.js";

/**
 * ListOrdersResponse is the response from a list request, it contains the paginated list of Orders.
 */
export interface ListOrdersResponse {
    /** LastPage is the identifier for the final page of results. It is only populated if there is another page of results after the current page. */
    lastPage?: number | undefined;
    /** NextPage is the identifier for the next page of results. It is only populated if there is another page of results after the current page. */
    nextPage?: number | undefined;
    /** TotalCount is total number of results. */
    totalCount: number;
    /** From specifies starting record number on current page. */
    from: number;
    /** To specifies ending record number on current page. */
    to: number;
    /** Orders is the collection of orders, if any, in the requesting account. */
    orders: Namecom.Order[];
    /** ParentAccountId field is populated when requesting account has a parent account id. */
    parentAccountId?: number | undefined;
}
