// This file was auto-generated by Fern from our API Definition.

/**
 * Error response returned when a resource is locked and cannot be modified. Used when the Add Grace Period (AGP) deletion window has expired.
 */
export interface Locked423 {
    /** A human-readable message providing more details about the error */
    message: string;
    /** Additional context or information about the error */
    details?: (string | null) | undefined;
}
