// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../index.js";

export interface ModifySubscriptionResponse {
    subscription?: Namecom.SubscriptionRecord | undefined;
}
