// This file was auto-generated by Fern from our API Definition.

/**
 * The list of nameservers assigned to this domain. If unspecified, it defaults to the account's default nameservers.
 */
export type Nameservers = string[];
