// This file was auto-generated by Fern from our API Definition.

export interface PremiumDomainsDownloadResponse {
    /** The pre-signed URL to use to download the list. */
    downloadUrl?: string | undefined;
    /** The timestamp that the URL will expire. */
    expireDate?: string | undefined;
}
