// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../index.js";

/**
 * PrivacyResponse contains the updated domain info as well as the order info for the newly purchased Whois Privacy.
 */
export interface PrivacyResponse {
    domain?: Namecom.DomainResponsePayload | undefined;
    /** Order is an identifier for this purchase. */
    order: number;
    /** TotalPaid is the total amount paid, including VAT. */
    totalPaid: number;
}
