// This file was auto-generated by Fern from our API Definition.

/**
 * Record is an individual DNS resource record.
 */
export interface Record_ {
    /**
     * Answer is either the IP address for A or AAAA records; the target for ANAME, CNAME, MX, or NS records; the text for TXT records.
     * For SRV records, answer has the following format: "{weight} {port} {target}" e.g. "1 5061 sip.example.org".
     */
    answer?: string | undefined;
    /** DomainName is the zone that the record belongs to. */
    domainName?: string | undefined;
    /** FQDN is the Fully Qualified Domain Name. It is the combination of the host and the domain name. It always ends in a ".". FQDN is ignored in CreateRecord, specify via the Host field instead. */
    fqdn?: string | undefined;
    /**
     * Host is the hostname relative to the zone: e.g. for a record for blog.example.org, domain would be "example.org" and host would be "blog".
     * An apex record would be specified by either an empty host "" or "@".
     * A SRV record would be specified by "_{service}._{protocol}.{host}": e.g. "_sip._tcp.phone" for _sip._tcp.phone.example.org.
     */
    host?: (string | null) | undefined;
    /** Unique record id. Value is ignored on Create, and must match the URI on Update. */
    id?: number | undefined;
    /** Priority is only required for MX and SRV records, it is ignored for all others. */
    priority?: number | undefined;
    /** TTL is the time this record can be cached for in seconds. name.com allows a minimum TTL of 300, or 5 minutes. */
    ttl: number;
    /** Type is one of the following: A, AAAA, ANAME, CNAME, MX, NS, SRV, or TXT. */
    type: string | null;
}
