// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../index.js";

/**
 * RefundResponse contains the results of a refund operation, including the individual order item results.
 * Refunds are issued to the original payment method on file. If the original payment method is unavailable, the refund will be credited to the account balance.
 */
export interface RefundResponse {
    /** An array of refund results for each order item that was processed. */
    results: Namecom.RefundItemResult[];
    /** The total amount refunded across all order items in USD. */
    totalRefundAmount: number;
}
