// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../index.js";

/**
 * RenewDomainResponse contains the updated domain info as well as the order info for the renewed domain.
 */
export interface RenewDomainResponse {
    domain?: Namecom.Domain | undefined;
    order?: number | undefined;
    /** TotalPaid is the total amount paid, including VAT. */
    totalPaid?: number | undefined;
}
