// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../index.js";

/**
 * An option within a field that has predefined choices, including the option value, label, and any nested fields that become relevant when this option is selected.
 */
export interface RequirementFieldOption {
    /** The actual value of this option. This is what must be submitted when this option is selected. */
    value: string;
    /** A user-friendly label for this option that can be displayed in UI forms. */
    label?: string | undefined;
    /** When this option is selected, these nested fields become relevant and may be required. This allows for conditional field logic. */
    fields?: (Record<string, Namecom.RequirementField | null> | null) | undefined;
}
