// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../index.js";

export interface SubscribeToNotificationResponse {
    subscription?: Namecom.SubscriptionRecord | undefined;
}
