// This file was auto-generated by Fern from our API Definition.

export interface SubscriptionRecord {
    active: boolean;
    createDate: string;
    eventName: string;
    id: number;
    updateDate: string | null;
    url: string;
}
