// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../index.js";

/**
 * A JSON Schema Draft 7 definition for tldInfo that wraps ResellerTldInfo with readOnly metadata. This schema can be referenced in JSON Schema documents using $ref.
 */
export type TldInfoJsonSchema = Namecom.ResellerTldInfo;
