// This file was auto-generated by Fern from our API Definition.

export interface TooManyRequestsErrorBody {
    /**
     * ### Too Many Requests
     * You have exceeded the rate limit.
     *
     * **Headers returned:**
     * * 'X-RateLimit-Reset': An integer (UTC epoch) indicating when you can retry.
     */
    message: string;
}
