// This file was auto-generated by Fern from our API Definition.

/**
 * Information about a specific trademark claim
 */
export interface TrademarkClaim {
    /** The trademark text that matches the domain */
    trademark: string;
    /** The entity that holds the trademark */
    holder: string;
    /** The jurisdiction where the trademark is registered */
    jurisdiction?: string | undefined;
    /** The trademark registration number */
    registrationNumber?: string | undefined;
    /** Additional description of the trademark */
    description?: string | undefined;
    /** HTML content to display about this specific trademark claim */
    noticeHtml?: string | undefined;
    /** Confidence score for the trademark match (0.0 to 1.0) */
    confidence?: number | undefined;
}
