// This file was auto-generated by Fern from our API Definition.

/**
 * Terminal (finished; will not change):
 * - **completed**: Completed.
 * - **failed**: Failed.
 * - **canceled**: Canceled by the user.
 * - **canceled_pending_refund**: Canceled; refund processing.
 *
 * Non-terminal (in progress; may change):
 * - **pending**: Requested.
 * - **submitting_transfer**: Being submitted to the registry.
 * - **pending_new_auth_code**: New auth code required.
 * - **pending_unlock**: Waiting for losing registrar unlock.
 * - **pending_registry_unlock**: Waiting for registry unlock.
 * - **pending_transfer**: Pending at the registry.
 * - **pending_insert**: Transfer complete; domain will be added to the account.
 * - **rejected**: Rejected at the losing registrar.
 */
export const TransferStatus = {
    Canceled: "canceled",
    CanceledPendingRefund: "canceled_pending_refund",
    Completed: "completed",
    Failed: "failed",
    Pending: "pending",
    PendingInsert: "pending_insert",
    PendingNewAuthCode: "pending_new_auth_code",
    PendingRegistryUnlock: "pending_registry_unlock",
    PendingTransfer: "pending_transfer",
    PendingUnlock: "pending_unlock",
    Rejected: "rejected",
    SubmittingTransfer: "submitting_transfer",
} as const;
export type TransferStatus = (typeof TransferStatus)[keyof typeof TransferStatus];
