// This file was auto-generated by Fern from our API Definition.

/**
 * Result of a transfer eligibility check. Indicates whether the domain is currently registered at name.com (in any account) and whether the TLD supports internal transfer between name.com accounts.
 */
export interface TransferEligibilityResponse {
    /** The domain that was checked, in its canonical (ASCII / punycode) form. */
    domainName: string;
    /** Whether the domain is currently registered at name.com (in any account). */
    atName: boolean;
    /** Whether the TLD supports internal transfer between name.com accounts. Mirrors the TLD-level flag returned by Get Tld Requirements. Does not reflect per-account allowlist eligibility for the internal transfer-in API. */
    supportsInternalTransfer: boolean;
}
