// This file was auto-generated by Fern from our API Definition.

export interface UnavailableForLegal451 {
    /** A human-readable message explaining why the resource is unavailable for legal reasons */
    message: string;
    /** Additional context or information about the legal restriction */
    details?: string | undefined;
}
