// This file was auto-generated by Fern from our API Definition.

/**
 * URLForwarding represents a URL forwarding entry, allowing a domain to redirect to another URL using different forwarding methods.
 */
export interface UrlForwarding {
    /** The domain name (without subdomains) that is being forwarded. */
    domainName?: string | undefined;
    /** The destination URL to which this hostname will be forwarded. */
    forwardsTo: string;
    /** The subdomain portion of the hostname that is being forwarded. */
    host: string;
    /**
     * Meta tags to include in the HTML page when using "masked" forwarding.
     * Ignored for other forwarding types.
     * Example: `<meta name='keywords' content='fish, denver, platte'>`
     */
    meta?: (string | null) | undefined;
    /**
     * The title to be used for the HTML page when using "masked" forwarding.
     * Ignored for other forwarding types.
     */
    title?: (string | null) | undefined;
    /**
     * The type of URL forwarding. Valid values:
     *   - `masked`: Retains the original domain in the address bar, preventing the user from seeing the actual destination URL. Sometimes called iframe forwarding.
     *   - `redirect`: Uses a standard HTTP redirect (301), which changes the address bar to the destination URL.
     *   - `302`: Uses a temporary HTTP redirect (302), which changes the address bar to the destination URL but indicates the resource is temporarily located elsewhere.
     */
    type: UrlForwarding.Type;
}

export namespace UrlForwarding {
    /**
     * The type of URL forwarding. Valid values:
     *   - `masked`: Retains the original domain in the address bar, preventing the user from seeing the actual destination URL. Sometimes called iframe forwarding.
     *   - `redirect`: Uses a standard HTTP redirect (301), which changes the address bar to the destination URL.
     *   - `302`: Uses a temporary HTTP redirect (302), which changes the address bar to the destination URL but indicates the resource is temporarily located elsewhere.
     */
    export const Type = {
        Masked: "masked",
        Redirect: "redirect",
        ThreeHundredTwo: "302",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
