// This file was auto-generated by Fern from our API Definition.

/**
 * Fields for updating a URL forwarding entry. Omit a property to leave it unchanged. An empty `host` string is the apex, not "unchanged".
 */
export interface UrlForwardingUpdate {
    /** The destination URL to which this hostname will be forwarded. */
    forwardsTo?: string | undefined;
    /** The subdomain portion of the hostname that is being forwarded. Omit this field to keep the existing host. Send an empty string to move the forwarding to the apex. */
    host?: string | undefined;
    /**
     * Meta tags to include in the HTML page when using "masked" forwarding.
     * Ignored for other forwarding types.
     * Example: `<meta name='keywords' content='fish, denver, platte'>`
     */
    meta?: (string | null) | undefined;
    /**
     * The title to be used for the HTML page when using "masked" forwarding.
     * Ignored for other forwarding types.
     */
    title?: (string | null) | undefined;
    /**
     * The type of URL forwarding. Valid values:
     *   - `masked`: Retains the original domain in the address bar, preventing the user from seeing the actual destination URL. Sometimes called iframe forwarding.
     *   - `redirect`: Uses a standard HTTP redirect (301), which changes the address bar to the destination URL.
     *   - `302`: Uses a temporary HTTP redirect (302), which changes the address bar to the destination URL but indicates the resource is temporarily located elsewhere.
     */
    type?: UrlForwardingUpdate.Type | undefined;
}

export namespace UrlForwardingUpdate {
    /**
     * The type of URL forwarding. Valid values:
     *   - `masked`: Retains the original domain in the address bar, preventing the user from seeing the actual destination URL. Sometimes called iframe forwarding.
     *   - `redirect`: Uses a standard HTTP redirect (301), which changes the address bar to the destination URL.
     *   - `302`: Uses a temporary HTTP redirect (302), which changes the address bar to the destination URL but indicates the resource is temporarily located elsewhere.
     */
    export const Type = {
        Masked: "masked",
        Redirect: "redirect",
        ThreeHundredTwo: "302",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
