// This file was auto-generated by Fern from our API Definition.

/**
 * VanityNameserver represents a custom nameserver associated with a domain, including its hostname and a list of IP addresses for glue records.
 */
export interface VanityNameserver {
    /** DomainName is the root domain for which this vanity nameserver is created. For example, if the hostname is 'ns1.example.com', the domainName would be 'example.com'. */
    domainName: string;
    /** Hostname is the fully qualified domain name (FQDN) of the vanity nameserver. It must be a subdomain of the domain specified in 'domainName'. */
    hostname: string;
    /** IPs is a list of IP addresses that are used for glue records for this vanity nameserver. These should be valid IPv4 or IPv6 addresses. */
    ips: string[];
}
