// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         domainName: "domainName",
 *         digest: "digest"
 *     }
 */
export interface DeleteDnssecRequest {
    /** DomainName is the domain name the key is registered for. */
    domainName: string;
    /** Digest is the digest for the DNSKEY RR to remove from the registry. */
    digest: string;
}
