// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: 1
 *     }
 */
export interface ModifySubscriptionRequest {
    /** ID of the subscription to update. */
    id: number;
    /** Optionally update the URL we send the webhook data to */
    url?: string;
    /** Optionally update if the subscription is currently active */
    active?: boolean;
}
