// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListOrdersRequest {
    /** Per Page is the number of records to return per request. Per Page defaults to 500. */
    perPage?: number;
    /** Page is which page to return. */
    page?: number;
    /** Dir indicates direction of list order. Possible values are 'asc' (default) or 'desc'. */
    dir?: string;
    /** DomainName filters orders by domain name. Supports exact match or wildcard (starts with '*'). */
    domainName?: string;
    /** Tld filters orders by tld. */
    tld?: string;
    /** CreateDateStart filters orders created on or after this date. */
    createDateStart?: string;
    /** CreateDateEnd filters orders created on or before this date. */
    createDateEnd?: string;
    /** Type filters orders by order item type (e.g., 'registration', 'renewal', 'transfer', 'whois_privacy'). */
    type?: string;
    /** OrderStatus filters orders by status. */
    orderStatus?: Namecom.ListOrdersRequestOrderStatus;
}
