// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../../../../index.js";

/**
 * @example
 *     {
 *         domainName: "example.com",
 *         body: {
 *             forwardsTo: "https://destination-site.com",
 *             host: "www",
 *             type: "masked"
 *         }
 *     }
 */
export interface CreateUrlForwardingRequest {
    /** DomainName is the domain part of the hostname to forward. */
    domainName: string;
    body: Namecom.CreateUrlForwardingBody;
}
