// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         domainName: "example.com",
 *         host: "www.example.org"
 *     }
 */
export interface DeleteUrlForwardingRequest {
    /** DomainName is the domain to delete the URL forwarding entry from. */
    domainName: string;
    /** The full hostname, including subdomain. */
    host: string;
}
