// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         domainName: "example.com",
 *         perPage: 100,
 *         page: 1
 *     }
 */
export interface ListUrlForwardingsByDomainRequest {
    /** DomainName is the domain to list URL forwarding entries for. The domain must be owned by the authenticated account. */
    domainName: string;
    /** Per Page is the number of records to return per request. Per Page defaults to 500. */
    perPage?: number;
    /** Page is which page to return. Starts at 1 for first page. */
    page?: number;
}
