// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../../../../index.js";

/**
 * @example
 *     {
 *         domainName: "example.com",
 *         host: "www.example.org",
 *         body: {
 *             forwardsTo: "https://destination-site.com",
 *             host: "www",
 *             type: "masked"
 *         }
 *     }
 */
export interface UpdateUrlForwardingRequest {
    /** DomainName is the domain part of the hostname to forward. */
    domainName: string;
    /** The full hostname, including subdomain. */
    host: string;
    body: Namecom.UrlForwardingInput;
}
