// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../../../../index.js";

/**
 * @example
 *     {
 *         domainName: "example.com",
 *         id: 12345,
 *         body: {
 *             forwardsTo: "https://destination-site.com",
 *             host: "www",
 *             type: "masked"
 *         }
 *     }
 */
export interface UpdateUrlForwardingByIdRequest {
    /** DomainName is the domain that owns the URL forwarding entry. Must be owned by the authenticated account. */
    domainName: string;
    /** ID is the server-assigned unique identifier for the URL forwarding record (returned in list responses). */
    id: number;
    body: Namecom.UrlForwardingInput;
}
