// This file was auto-generated by Fern from our API Definition.

import * as Namecom from "../../src/api/index";
import { NamecomClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AccountsClient", () => {
    test("CreateAccount (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            account: {
                accountName: "reseller_subaccount",
                contacts: {
                    registrant: {
                        firstName: "Jane",
                        lastName: "Doe",
                        address1: "123 Main St.",
                        city: "Denver",
                        state: "CO",
                        zip: "12345",
                        country: "US",
                        email: "admin@example.net",
                        phone: "+13035551212",
                    },
                },
                password: "SecureP4ss!",
            },
            apiTos: true,
            tos: true,
        };
        const rawResponseBody = {
            accountName: "new_reseller_account",
            apiToken: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            apiTokenName: "my_reseller_token",
        };

        server
            .mockEndpoint()
            .post("/core/v1/accounts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.accounts.createAccount({
            account: {
                accountName: "reseller_subaccount",
                contacts: {
                    registrant: {
                        firstName: "Jane",
                        lastName: "Doe",
                        address1: "123 Main St.",
                        city: "Denver",
                        state: "CO",
                        zip: "12345",
                        country: "US",
                        email: "admin@example.net",
                        phone: "+13035551212",
                    },
                },
                password: "SecureP4ss!",
            },
            apiTos: true,
            tos: true,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("CreateAccount (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { account: {}, apiTos: true, tos: true };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/accounts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.accounts.createAccount({
                account: {},
                apiTos: true,
                tos: true,
            });
        }).rejects.toThrow(Namecom.BadRequestError);
    });

    test("CreateAccount (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { account: {}, apiTos: true, tos: true };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/accounts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.accounts.createAccount({
                account: {},
                apiTos: true,
                tos: true,
            });
        }).rejects.toThrow(Namecom.UnauthorizedError);
    });

    test("CreateAccount (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { account: {}, apiTos: true, tos: true };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/accounts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.accounts.createAccount({
                account: {},
                apiTos: true,
                tos: true,
            });
        }).rejects.toThrow(Namecom.ForbiddenError);
    });

    test("CreateAccount (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { account: {}, apiTos: true, tos: true };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/accounts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.accounts.createAccount({
                account: {},
                apiTos: true,
                tos: true,
            });
        }).rejects.toThrow(Namecom.MethodNotAllowedError);
    });

    test("CreateAccount (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { account: {}, apiTos: true, tos: true };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/core/v1/accounts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(415)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.accounts.createAccount({
                account: {},
                apiTos: true,
                tos: true,
            });
        }).rejects.toThrow(Namecom.UnsupportedMediaTypeError);
    });

    test("CreateAccount (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { account: {}, apiTos: true, tos: true };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/accounts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.accounts.createAccount({
                account: {},
                apiTos: true,
                tos: true,
            });
        }).rejects.toThrow(Namecom.TooManyRequestsError);
    });

    test("CreateAccount (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { account: {}, apiTos: true, tos: true };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/accounts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.accounts.createAccount({
                account: {},
                apiTos: true,
                tos: true,
            });
        }).rejects.toThrow(Namecom.InternalServerError);
    });

    test("CreateAccount (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { account: {}, apiTos: true, tos: true };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/accounts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.accounts.createAccount({
                account: {},
                apiTos: true,
                tos: true,
            });
        }).rejects.toThrow(Namecom.BadGatewayError);
    });

    test("CreateAccount (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { account: {}, apiTos: true, tos: true };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/accounts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.accounts.createAccount({
                account: {},
                apiTos: true,
                tos: true,
            });
        }).rejects.toThrow(Namecom.GatewayTimeoutError);
    });
});
