// This file was auto-generated by Fern from our API Definition.

import * as Namecom from "../../src/api/index";
import { NamecomClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ContactVerificationClient", () => {
    test("UnverifiedContactsList (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            unverifiedContacts: [
                {
                    verificationId: 4897668,
                    createDate: "2025-01-01T15:35:06Z",
                    verifyBy: "2025-01-16T15:35:06Z",
                    email: "admin@example.com",
                    domains: ["domains"],
                },
            ],
            from: 1,
            to: 25,
            lastPage: 1,
            nextPage: 1,
            totalCount: 1,
        };

        server
            .mockEndpoint()
            .get("/core/v1/contacts/unverified")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contactVerification.unverifiedContactsList({
            perPage: 100,
            page: 2,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("UnverifiedContactsList (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/contacts/unverified")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contactVerification.unverifiedContactsList();
        }).rejects.toThrow(Namecom.UnauthorizedError);
    });

    test("UnverifiedContactsList (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/contacts/unverified")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contactVerification.unverifiedContactsList();
        }).rejects.toThrow(Namecom.ForbiddenError);
    });

    test("UnverifiedContactsList (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/contacts/unverified")
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contactVerification.unverifiedContactsList();
        }).rejects.toThrow(Namecom.MethodNotAllowedError);
    });

    test("UnverifiedContactsList (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/contacts/unverified")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contactVerification.unverifiedContactsList();
        }).rejects.toThrow(Namecom.TooManyRequestsError);
    });

    test("UnverifiedContactsList (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/contacts/unverified")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contactVerification.unverifiedContactsList();
        }).rejects.toThrow(Namecom.InternalServerError);
    });

    test("UnverifiedContactsList (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/contacts/unverified")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contactVerification.unverifiedContactsList();
        }).rejects.toThrow(Namecom.BadGatewayError);
    });

    test("UnverifiedContactsList (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/contacts/unverified")
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contactVerification.unverifiedContactsList();
        }).rejects.toThrow(Namecom.GatewayTimeoutError);
    });

    test("VerifyContact (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        server
            .mockEndpoint()
            .post("/core/v1/contacts/verify/1")
            .header("X-Idempotency-Key", "083910ef-04e4-4bd1-a0bf-3737fe005ca8")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.contactVerification.verifyContact({
            "X-Idempotency-Key": "083910ef-04e4-4bd1-a0bf-3737fe005ca8",
            verificationId: 1,
        });
        expect(response).toEqual(undefined);
    });

    test("VerifyContact (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/contacts/verify/1")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contactVerification.verifyContact({
                verificationId: 1,
            });
        }).rejects.toThrow(Namecom.UnauthorizedError);
    });

    test("VerifyContact (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/contacts/verify/1")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contactVerification.verifyContact({
                verificationId: 1,
            });
        }).rejects.toThrow(Namecom.ForbiddenError);
    });

    test("VerifyContact (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/core/v1/contacts/verify/1")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contactVerification.verifyContact({
                verificationId: 1,
            });
        }).rejects.toThrow(Namecom.NotFoundError);
    });

    test("VerifyContact (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/contacts/verify/1")
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contactVerification.verifyContact({
                verificationId: 1,
            });
        }).rejects.toThrow(Namecom.MethodNotAllowedError);
    });

    test("VerifyContact (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/contacts/verify/1")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contactVerification.verifyContact({
                verificationId: 1,
            });
        }).rejects.toThrow(Namecom.ConflictError);
    });

    test("VerifyContact (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/core/v1/contacts/verify/1")
            .respondWith()
            .statusCode(415)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contactVerification.verifyContact({
                verificationId: 1,
            });
        }).rejects.toThrow(Namecom.UnsupportedMediaTypeError);
    });

    test("VerifyContact (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/contacts/verify/1")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contactVerification.verifyContact({
                verificationId: 1,
            });
        }).rejects.toThrow(Namecom.TooManyRequestsError);
    });

    test("VerifyContact (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/contacts/verify/1")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contactVerification.verifyContact({
                verificationId: 1,
            });
        }).rejects.toThrow(Namecom.InternalServerError);
    });

    test("VerifyContact (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/contacts/verify/1")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contactVerification.verifyContact({
                verificationId: 1,
            });
        }).rejects.toThrow(Namecom.BadGatewayError);
    });

    test("VerifyContact (11)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/contacts/verify/1")
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contactVerification.verifyContact({
                verificationId: 1,
            });
        }).rejects.toThrow(Namecom.GatewayTimeoutError);
    });

    test("ResendContactVerificationEmail (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { sent: true, verificationId: 98752463, nextEligibleAt: "2026-01-14T12:15:00Z" };

        server
            .mockEndpoint()
            .post("/core/v1/contacts/verify/1:resend")
            .header("X-Idempotency-Key", "083910ef-04e4-4bd1-a0bf-3737fe005ca8")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contactVerification.resendContactVerificationEmail({
            "X-Idempotency-Key": "083910ef-04e4-4bd1-a0bf-3737fe005ca8",
            verificationId: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("ResendContactVerificationEmail (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { sent: false, verificationId: 98752463, nextEligibleAt: "2026-01-14T12:00:00Z" };

        server
            .mockEndpoint()
            .post("/core/v1/contacts/verify/1:resend")
            .header("X-Idempotency-Key", "083910ef-04e4-4bd1-a0bf-3737fe005ca8")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contactVerification.resendContactVerificationEmail({
            "X-Idempotency-Key": "083910ef-04e4-4bd1-a0bf-3737fe005ca8",
            verificationId: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("ResendContactVerificationEmail (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/contacts/verify/1:resend")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contactVerification.resendContactVerificationEmail({
                verificationId: 1,
            });
        }).rejects.toThrow(Namecom.UnauthorizedError);
    });

    test("ResendContactVerificationEmail (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/contacts/verify/1:resend")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contactVerification.resendContactVerificationEmail({
                verificationId: 1,
            });
        }).rejects.toThrow(Namecom.ForbiddenError);
    });

    test("ResendContactVerificationEmail (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/core/v1/contacts/verify/1:resend")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contactVerification.resendContactVerificationEmail({
                verificationId: 1,
            });
        }).rejects.toThrow(Namecom.NotFoundError);
    });

    test("ResendContactVerificationEmail (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/contacts/verify/1:resend")
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contactVerification.resendContactVerificationEmail({
                verificationId: 1,
            });
        }).rejects.toThrow(Namecom.MethodNotAllowedError);
    });

    test("ResendContactVerificationEmail (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/contacts/verify/1:resend")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contactVerification.resendContactVerificationEmail({
                verificationId: 1,
            });
        }).rejects.toThrow(Namecom.ConflictError);
    });

    test("ResendContactVerificationEmail (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/core/v1/contacts/verify/1:resend")
            .respondWith()
            .statusCode(415)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contactVerification.resendContactVerificationEmail({
                verificationId: 1,
            });
        }).rejects.toThrow(Namecom.UnsupportedMediaTypeError);
    });

    test("ResendContactVerificationEmail (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/contacts/verify/1:resend")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contactVerification.resendContactVerificationEmail({
                verificationId: 1,
            });
        }).rejects.toThrow(Namecom.TooManyRequestsError);
    });

    test("ResendContactVerificationEmail (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/contacts/verify/1:resend")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contactVerification.resendContactVerificationEmail({
                verificationId: 1,
            });
        }).rejects.toThrow(Namecom.InternalServerError);
    });

    test("ResendContactVerificationEmail (11)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/contacts/verify/1:resend")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contactVerification.resendContactVerificationEmail({
                verificationId: 1,
            });
        }).rejects.toThrow(Namecom.BadGatewayError);
    });

    test("ResendContactVerificationEmail (12)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/contacts/verify/1:resend")
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contactVerification.resendContactVerificationEmail({
                verificationId: 1,
            });
        }).rejects.toThrow(Namecom.GatewayTimeoutError);
    });
});
