// This file was auto-generated by Fern from our API Definition.

import * as Namecom from "../../src/api/index";
import { NamecomClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("DnsClient", () => {
    test("ListRecords (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            lastPage: 1,
            nextPage: 1,
            totalCount: 1,
            from: 1,
            to: 1,
            records: [
                {
                    answer: "answer",
                    domainName: "domainName",
                    fqdn: "fqdn",
                    host: "host",
                    id: 1,
                    priority: 1000000,
                    ttl: 1000000,
                    type: "type",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/records")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.dns.listRecords({
            domainName: "domainName",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("ListRecords (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/records")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.listRecords({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.BadRequestError);
    });

    test("ListRecords (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/records")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.listRecords({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.UnauthorizedError);
    });

    test("ListRecords (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/records")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.listRecords({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.ForbiddenError);
    });

    test("ListRecords (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/records")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.listRecords({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.NotFoundError);
    });

    test("ListRecords (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/records")
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.listRecords({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.MethodNotAllowedError);
    });

    test("ListRecords (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/records")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.listRecords({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.TooManyRequestsError);
    });

    test("ListRecords (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/records")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.listRecords({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.InternalServerError);
    });

    test("ListRecords (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/records")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.listRecords({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.BadGatewayError);
    });

    test("ListRecords (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/records")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.listRecords({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.ServiceUnavailableError);
    });

    test("ListRecords (11)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/records")
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.listRecords({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.GatewayTimeoutError);
    });

    test("CreateRecord (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { answer: "answer", host: "host", type: "A" };
        const rawResponseBody = {
            answer: "answer",
            domainName: "domainName",
            fqdn: "fqdn",
            host: "host",
            id: 1,
            priority: 1000000,
            ttl: 1000000,
            type: "type",
        };

        server
            .mockEndpoint()
            .post("/core/v1/domains/domainName/records")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.dns.createRecord({
            domainName: "domainName",
            answer: "answer",
            host: "host",
            type: "A",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("CreateRecord (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { answer: "x", host: "host", type: "A" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/domains/domainName/records")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.createRecord({
                domainName: "domainName",
                answer: "x",
                host: "host",
                type: "A",
            });
        }).rejects.toThrow(Namecom.BadRequestError);
    });

    test("CreateRecord (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { answer: "x", host: "host", type: "A" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/domains/domainName/records")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.createRecord({
                domainName: "domainName",
                answer: "x",
                host: "host",
                type: "A",
            });
        }).rejects.toThrow(Namecom.UnauthorizedError);
    });

    test("CreateRecord (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { answer: "x", host: "host", type: "A" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/domains/domainName/records")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.createRecord({
                domainName: "domainName",
                answer: "x",
                host: "host",
                type: "A",
            });
        }).rejects.toThrow(Namecom.ForbiddenError);
    });

    test("CreateRecord (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { answer: "x", host: "host", type: "A" };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/core/v1/domains/domainName/records")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.createRecord({
                domainName: "domainName",
                answer: "x",
                host: "host",
                type: "A",
            });
        }).rejects.toThrow(Namecom.NotFoundError);
    });

    test("CreateRecord (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { answer: "x", host: "host", type: "A" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/domains/domainName/records")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.createRecord({
                domainName: "domainName",
                answer: "x",
                host: "host",
                type: "A",
            });
        }).rejects.toThrow(Namecom.MethodNotAllowedError);
    });

    test("CreateRecord (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { answer: "x", host: "host", type: "A" };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/core/v1/domains/domainName/records")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(415)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.createRecord({
                domainName: "domainName",
                answer: "x",
                host: "host",
                type: "A",
            });
        }).rejects.toThrow(Namecom.UnsupportedMediaTypeError);
    });

    test("CreateRecord (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { answer: "x", host: "host", type: "A" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/domains/domainName/records")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.createRecord({
                domainName: "domainName",
                answer: "x",
                host: "host",
                type: "A",
            });
        }).rejects.toThrow(Namecom.TooManyRequestsError);
    });

    test("CreateRecord (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { answer: "x", host: "host", type: "A" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/domains/domainName/records")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.createRecord({
                domainName: "domainName",
                answer: "x",
                host: "host",
                type: "A",
            });
        }).rejects.toThrow(Namecom.InternalServerError);
    });

    test("CreateRecord (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { answer: "x", host: "host", type: "A" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/domains/domainName/records")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.createRecord({
                domainName: "domainName",
                answer: "x",
                host: "host",
                type: "A",
            });
        }).rejects.toThrow(Namecom.BadGatewayError);
    });

    test("CreateRecord (11)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { answer: "x", host: "host", type: "A" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/domains/domainName/records")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.createRecord({
                domainName: "domainName",
                answer: "x",
                host: "host",
                type: "A",
            });
        }).rejects.toThrow(Namecom.ServiceUnavailableError);
    });

    test("CreateRecord (12)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { answer: "x", host: "host", type: "A" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/domains/domainName/records")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.createRecord({
                domainName: "domainName",
                answer: "x",
                host: "host",
                type: "A",
            });
        }).rejects.toThrow(Namecom.GatewayTimeoutError);
    });

    test("GetRecord (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            answer: "answer",
            domainName: "domainName",
            fqdn: "fqdn",
            host: "host",
            id: 1,
            priority: 1000000,
            ttl: 1000000,
            type: "type",
        };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/records/1")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.dns.getRecord({
            domainName: "domainName",
            id: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("GetRecord (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/records/1")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.getRecord({
                domainName: "domainName",
                id: 1,
            });
        }).rejects.toThrow(Namecom.UnauthorizedError);
    });

    test("GetRecord (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/records/1")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.getRecord({
                domainName: "domainName",
                id: 1,
            });
        }).rejects.toThrow(Namecom.ForbiddenError);
    });

    test("GetRecord (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/records/1")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.getRecord({
                domainName: "domainName",
                id: 1,
            });
        }).rejects.toThrow(Namecom.NotFoundError);
    });

    test("GetRecord (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/records/1")
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.getRecord({
                domainName: "domainName",
                id: 1,
            });
        }).rejects.toThrow(Namecom.MethodNotAllowedError);
    });

    test("GetRecord (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/records/1")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.getRecord({
                domainName: "domainName",
                id: 1,
            });
        }).rejects.toThrow(Namecom.TooManyRequestsError);
    });

    test("GetRecord (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/records/1")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.getRecord({
                domainName: "domainName",
                id: 1,
            });
        }).rejects.toThrow(Namecom.InternalServerError);
    });

    test("GetRecord (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/records/1")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.getRecord({
                domainName: "domainName",
                id: 1,
            });
        }).rejects.toThrow(Namecom.BadGatewayError);
    });

    test("GetRecord (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/records/1")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.getRecord({
                domainName: "domainName",
                id: 1,
            });
        }).rejects.toThrow(Namecom.ServiceUnavailableError);
    });

    test("GetRecord (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/records/1")
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.getRecord({
                domainName: "domainName",
                id: 1,
            });
        }).rejects.toThrow(Namecom.GatewayTimeoutError);
    });

    test("UpdateRecord (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { answer: "answer", type: "A" };
        const rawResponseBody = {
            answer: "answer",
            domainName: "domainName",
            fqdn: "fqdn",
            host: "host",
            id: 1,
            priority: 1000000,
            ttl: 1000000,
            type: "type",
        };

        server
            .mockEndpoint()
            .put("/core/v1/domains/domainName/records/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.dns.updateRecord({
            domainName: "domainName",
            id: 1,
            answer: "answer",
            type: "A",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("UpdateRecord (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { answer: "x", type: "A" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/core/v1/domains/domainName/records/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.updateRecord({
                domainName: "domainName",
                id: 1,
                answer: "x",
                type: "A",
            });
        }).rejects.toThrow(Namecom.BadRequestError);
    });

    test("UpdateRecord (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { answer: "x", type: "A" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/core/v1/domains/domainName/records/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.updateRecord({
                domainName: "domainName",
                id: 1,
                answer: "x",
                type: "A",
            });
        }).rejects.toThrow(Namecom.UnauthorizedError);
    });

    test("UpdateRecord (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { answer: "x", type: "A" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/core/v1/domains/domainName/records/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.updateRecord({
                domainName: "domainName",
                id: 1,
                answer: "x",
                type: "A",
            });
        }).rejects.toThrow(Namecom.ForbiddenError);
    });

    test("UpdateRecord (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { answer: "x", type: "A" };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .put("/core/v1/domains/domainName/records/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.updateRecord({
                domainName: "domainName",
                id: 1,
                answer: "x",
                type: "A",
            });
        }).rejects.toThrow(Namecom.NotFoundError);
    });

    test("UpdateRecord (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { answer: "x", type: "A" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/core/v1/domains/domainName/records/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.updateRecord({
                domainName: "domainName",
                id: 1,
                answer: "x",
                type: "A",
            });
        }).rejects.toThrow(Namecom.MethodNotAllowedError);
    });

    test("UpdateRecord (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { answer: "x", type: "A" };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .put("/core/v1/domains/domainName/records/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(415)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.updateRecord({
                domainName: "domainName",
                id: 1,
                answer: "x",
                type: "A",
            });
        }).rejects.toThrow(Namecom.UnsupportedMediaTypeError);
    });

    test("UpdateRecord (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { answer: "x", type: "A" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/core/v1/domains/domainName/records/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.updateRecord({
                domainName: "domainName",
                id: 1,
                answer: "x",
                type: "A",
            });
        }).rejects.toThrow(Namecom.TooManyRequestsError);
    });

    test("UpdateRecord (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { answer: "x", type: "A" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/core/v1/domains/domainName/records/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.updateRecord({
                domainName: "domainName",
                id: 1,
                answer: "x",
                type: "A",
            });
        }).rejects.toThrow(Namecom.InternalServerError);
    });

    test("UpdateRecord (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { answer: "x", type: "A" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/core/v1/domains/domainName/records/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.updateRecord({
                domainName: "domainName",
                id: 1,
                answer: "x",
                type: "A",
            });
        }).rejects.toThrow(Namecom.BadGatewayError);
    });

    test("UpdateRecord (11)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { answer: "x", type: "A" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/core/v1/domains/domainName/records/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.updateRecord({
                domainName: "domainName",
                id: 1,
                answer: "x",
                type: "A",
            });
        }).rejects.toThrow(Namecom.ServiceUnavailableError);
    });

    test("UpdateRecord (12)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { answer: "x", type: "A" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/core/v1/domains/domainName/records/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.updateRecord({
                domainName: "domainName",
                id: 1,
                answer: "x",
                type: "A",
            });
        }).rejects.toThrow(Namecom.GatewayTimeoutError);
    });

    test("DeleteRecord (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        server.mockEndpoint().delete("/core/v1/domains/domainName/records/1").respondWith().statusCode(200).build();

        const response = await client.dns.deleteRecord({
            domainName: "domainName",
            id: 1,
        });
        expect(response).toEqual(undefined);
    });

    test("DeleteRecord (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/core/v1/domains/domainName/records/1")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.deleteRecord({
                domainName: "domainName",
                id: 1,
            });
        }).rejects.toThrow(Namecom.BadRequestError);
    });

    test("DeleteRecord (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/core/v1/domains/domainName/records/1")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.deleteRecord({
                domainName: "domainName",
                id: 1,
            });
        }).rejects.toThrow(Namecom.UnauthorizedError);
    });

    test("DeleteRecord (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/core/v1/domains/domainName/records/1")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.deleteRecord({
                domainName: "domainName",
                id: 1,
            });
        }).rejects.toThrow(Namecom.ForbiddenError);
    });

    test("DeleteRecord (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .delete("/core/v1/domains/domainName/records/1")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.deleteRecord({
                domainName: "domainName",
                id: 1,
            });
        }).rejects.toThrow(Namecom.NotFoundError);
    });

    test("DeleteRecord (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/core/v1/domains/domainName/records/1")
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.deleteRecord({
                domainName: "domainName",
                id: 1,
            });
        }).rejects.toThrow(Namecom.MethodNotAllowedError);
    });

    test("DeleteRecord (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/core/v1/domains/domainName/records/1")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.deleteRecord({
                domainName: "domainName",
                id: 1,
            });
        }).rejects.toThrow(Namecom.TooManyRequestsError);
    });

    test("DeleteRecord (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/core/v1/domains/domainName/records/1")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.deleteRecord({
                domainName: "domainName",
                id: 1,
            });
        }).rejects.toThrow(Namecom.InternalServerError);
    });

    test("DeleteRecord (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/core/v1/domains/domainName/records/1")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.deleteRecord({
                domainName: "domainName",
                id: 1,
            });
        }).rejects.toThrow(Namecom.BadGatewayError);
    });

    test("DeleteRecord (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/core/v1/domains/domainName/records/1")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.deleteRecord({
                domainName: "domainName",
                id: 1,
            });
        }).rejects.toThrow(Namecom.ServiceUnavailableError);
    });

    test("DeleteRecord (11)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/core/v1/domains/domainName/records/1")
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.dns.deleteRecord({
                domainName: "domainName",
                id: 1,
            });
        }).rejects.toThrow(Namecom.GatewayTimeoutError);
    });
});
