// This file was auto-generated by Fern from our API Definition.

import * as Namecom from "../../src/api/index";
import { NamecomClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("EmailForwardingsClient", () => {
    test("ListEmailForwardings (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            emailForwarding: [{ domainName: "example.com", emailBox: "admin", emailTo: "webmaster@example.com" }],
            lastPage: 1,
            nextPage: 1,
        };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/email/forwarding")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.emailForwardings.listEmailForwardings({
            domainName: "domainName",
            perPage: 100,
            page: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("ListEmailForwardings (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/email/forwarding")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.listEmailForwardings({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.BadRequestError);
    });

    test("ListEmailForwardings (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/email/forwarding")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.listEmailForwardings({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.UnauthorizedError);
    });

    test("ListEmailForwardings (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/email/forwarding")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.listEmailForwardings({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.ForbiddenError);
    });

    test("ListEmailForwardings (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/email/forwarding")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.listEmailForwardings({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.NotFoundError);
    });

    test("ListEmailForwardings (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/email/forwarding")
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.listEmailForwardings({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.MethodNotAllowedError);
    });

    test("ListEmailForwardings (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/email/forwarding")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.listEmailForwardings({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.TooManyRequestsError);
    });

    test("ListEmailForwardings (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/email/forwarding")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.listEmailForwardings({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.InternalServerError);
    });

    test("ListEmailForwardings (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/email/forwarding")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.listEmailForwardings({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.BadGatewayError);
    });

    test("ListEmailForwardings (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/email/forwarding")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.listEmailForwardings({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.ServiceUnavailableError);
    });

    test("ListEmailForwardings (11)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/email/forwarding")
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.listEmailForwardings({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.GatewayTimeoutError);
    });

    test("CreateEmailForwarding (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { emailBox: "admin", emailTo: "webmaster@example.com" };
        const rawResponseBody = { domainName: "example.com", emailBox: "admin", emailTo: "webmaster@example.com" };

        server
            .mockEndpoint()
            .post("/core/v1/domains/example.com/email/forwarding")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.emailForwardings.createEmailForwarding({
            domainName: "example.com",
            emailBox: "admin",
            emailTo: "webmaster@example.com",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("CreateEmailForwarding (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { emailBox: "x", emailTo: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/domains/domainName/email/forwarding")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.createEmailForwarding({
                domainName: "domainName",
                emailBox: "x",
                emailTo: "x",
            });
        }).rejects.toThrow(Namecom.BadRequestError);
    });

    test("CreateEmailForwarding (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { emailBox: "x", emailTo: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/domains/domainName/email/forwarding")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.createEmailForwarding({
                domainName: "domainName",
                emailBox: "x",
                emailTo: "x",
            });
        }).rejects.toThrow(Namecom.UnauthorizedError);
    });

    test("CreateEmailForwarding (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { emailBox: "x", emailTo: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/domains/domainName/email/forwarding")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.createEmailForwarding({
                domainName: "domainName",
                emailBox: "x",
                emailTo: "x",
            });
        }).rejects.toThrow(Namecom.ForbiddenError);
    });

    test("CreateEmailForwarding (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { emailBox: "x", emailTo: "x" };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/core/v1/domains/domainName/email/forwarding")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.createEmailForwarding({
                domainName: "domainName",
                emailBox: "x",
                emailTo: "x",
            });
        }).rejects.toThrow(Namecom.NotFoundError);
    });

    test("CreateEmailForwarding (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { emailBox: "x", emailTo: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/domains/domainName/email/forwarding")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.createEmailForwarding({
                domainName: "domainName",
                emailBox: "x",
                emailTo: "x",
            });
        }).rejects.toThrow(Namecom.MethodNotAllowedError);
    });

    test("CreateEmailForwarding (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { emailBox: "x", emailTo: "x" };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/core/v1/domains/domainName/email/forwarding")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(415)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.createEmailForwarding({
                domainName: "domainName",
                emailBox: "x",
                emailTo: "x",
            });
        }).rejects.toThrow(Namecom.UnsupportedMediaTypeError);
    });

    test("CreateEmailForwarding (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { emailBox: "x", emailTo: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/domains/domainName/email/forwarding")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.createEmailForwarding({
                domainName: "domainName",
                emailBox: "x",
                emailTo: "x",
            });
        }).rejects.toThrow(Namecom.TooManyRequestsError);
    });

    test("CreateEmailForwarding (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { emailBox: "x", emailTo: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/domains/domainName/email/forwarding")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.createEmailForwarding({
                domainName: "domainName",
                emailBox: "x",
                emailTo: "x",
            });
        }).rejects.toThrow(Namecom.InternalServerError);
    });

    test("CreateEmailForwarding (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { emailBox: "x", emailTo: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/domains/domainName/email/forwarding")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.createEmailForwarding({
                domainName: "domainName",
                emailBox: "x",
                emailTo: "x",
            });
        }).rejects.toThrow(Namecom.BadGatewayError);
    });

    test("CreateEmailForwarding (11)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { emailBox: "x", emailTo: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/domains/domainName/email/forwarding")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.createEmailForwarding({
                domainName: "domainName",
                emailBox: "x",
                emailTo: "x",
            });
        }).rejects.toThrow(Namecom.ServiceUnavailableError);
    });

    test("CreateEmailForwarding (12)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { emailBox: "x", emailTo: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/domains/domainName/email/forwarding")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.createEmailForwarding({
                domainName: "domainName",
                emailBox: "x",
                emailTo: "x",
            });
        }).rejects.toThrow(Namecom.GatewayTimeoutError);
    });

    test("GetEmailForwarding (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { domainName: "example.com", emailBox: "admin", emailTo: "webmaster@example.com" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/email/forwarding/emailBox")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.emailForwardings.getEmailForwarding({
            domainName: "domainName",
            emailBox: "emailBox",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("GetEmailForwarding (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/email/forwarding/emailBox")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.getEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
            });
        }).rejects.toThrow(Namecom.UnauthorizedError);
    });

    test("GetEmailForwarding (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/email/forwarding/emailBox")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.getEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
            });
        }).rejects.toThrow(Namecom.ForbiddenError);
    });

    test("GetEmailForwarding (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/email/forwarding/emailBox")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.getEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
            });
        }).rejects.toThrow(Namecom.NotFoundError);
    });

    test("GetEmailForwarding (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/email/forwarding/emailBox")
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.getEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
            });
        }).rejects.toThrow(Namecom.MethodNotAllowedError);
    });

    test("GetEmailForwarding (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/email/forwarding/emailBox")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.getEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
            });
        }).rejects.toThrow(Namecom.TooManyRequestsError);
    });

    test("GetEmailForwarding (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/email/forwarding/emailBox")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.getEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
            });
        }).rejects.toThrow(Namecom.InternalServerError);
    });

    test("GetEmailForwarding (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/email/forwarding/emailBox")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.getEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
            });
        }).rejects.toThrow(Namecom.BadGatewayError);
    });

    test("GetEmailForwarding (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/email/forwarding/emailBox")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.getEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
            });
        }).rejects.toThrow(Namecom.ServiceUnavailableError);
    });

    test("GetEmailForwarding (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/domains/domainName/email/forwarding/emailBox")
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.getEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
            });
        }).rejects.toThrow(Namecom.GatewayTimeoutError);
    });

    test("UpdateEmailForwarding (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { emailTo: "emailTo" };
        const rawResponseBody = { domainName: "example.com", emailBox: "admin", emailTo: "webmaster@example.com" };

        server
            .mockEndpoint()
            .put("/core/v1/domains/domainName/email/forwarding/emailBox")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.emailForwardings.updateEmailForwarding({
            domainName: "domainName",
            emailBox: "emailBox",
            emailTo: "emailTo",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("UpdateEmailForwarding (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { emailTo: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/core/v1/domains/domainName/email/forwarding/emailBox")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.updateEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
                emailTo: "x",
            });
        }).rejects.toThrow(Namecom.UnauthorizedError);
    });

    test("UpdateEmailForwarding (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { emailTo: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/core/v1/domains/domainName/email/forwarding/emailBox")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.updateEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
                emailTo: "x",
            });
        }).rejects.toThrow(Namecom.ForbiddenError);
    });

    test("UpdateEmailForwarding (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { emailTo: "x" };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .put("/core/v1/domains/domainName/email/forwarding/emailBox")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.updateEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
                emailTo: "x",
            });
        }).rejects.toThrow(Namecom.NotFoundError);
    });

    test("UpdateEmailForwarding (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { emailTo: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/core/v1/domains/domainName/email/forwarding/emailBox")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.updateEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
                emailTo: "x",
            });
        }).rejects.toThrow(Namecom.MethodNotAllowedError);
    });

    test("UpdateEmailForwarding (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { emailTo: "x" };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .put("/core/v1/domains/domainName/email/forwarding/emailBox")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(415)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.updateEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
                emailTo: "x",
            });
        }).rejects.toThrow(Namecom.UnsupportedMediaTypeError);
    });

    test("UpdateEmailForwarding (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { emailTo: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/core/v1/domains/domainName/email/forwarding/emailBox")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.updateEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
                emailTo: "x",
            });
        }).rejects.toThrow(Namecom.TooManyRequestsError);
    });

    test("UpdateEmailForwarding (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { emailTo: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/core/v1/domains/domainName/email/forwarding/emailBox")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.updateEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
                emailTo: "x",
            });
        }).rejects.toThrow(Namecom.InternalServerError);
    });

    test("UpdateEmailForwarding (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { emailTo: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/core/v1/domains/domainName/email/forwarding/emailBox")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.updateEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
                emailTo: "x",
            });
        }).rejects.toThrow(Namecom.BadGatewayError);
    });

    test("UpdateEmailForwarding (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { emailTo: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/core/v1/domains/domainName/email/forwarding/emailBox")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.updateEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
                emailTo: "x",
            });
        }).rejects.toThrow(Namecom.ServiceUnavailableError);
    });

    test("UpdateEmailForwarding (11)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { emailTo: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/core/v1/domains/domainName/email/forwarding/emailBox")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.updateEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
                emailTo: "x",
            });
        }).rejects.toThrow(Namecom.GatewayTimeoutError);
    });

    test("DeleteEmailForwarding (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        server
            .mockEndpoint()
            .delete("/core/v1/domains/domainName/email/forwarding/emailBox")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.emailForwardings.deleteEmailForwarding({
            domainName: "domainName",
            emailBox: "emailBox",
        });
        expect(response).toEqual(undefined);
    });

    test("DeleteEmailForwarding (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/core/v1/domains/domainName/email/forwarding/emailBox")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.deleteEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
            });
        }).rejects.toThrow(Namecom.UnauthorizedError);
    });

    test("DeleteEmailForwarding (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/core/v1/domains/domainName/email/forwarding/emailBox")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.deleteEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
            });
        }).rejects.toThrow(Namecom.ForbiddenError);
    });

    test("DeleteEmailForwarding (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .delete("/core/v1/domains/domainName/email/forwarding/emailBox")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.deleteEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
            });
        }).rejects.toThrow(Namecom.NotFoundError);
    });

    test("DeleteEmailForwarding (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/core/v1/domains/domainName/email/forwarding/emailBox")
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.deleteEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
            });
        }).rejects.toThrow(Namecom.MethodNotAllowedError);
    });

    test("DeleteEmailForwarding (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/core/v1/domains/domainName/email/forwarding/emailBox")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.deleteEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
            });
        }).rejects.toThrow(Namecom.TooManyRequestsError);
    });

    test("DeleteEmailForwarding (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/core/v1/domains/domainName/email/forwarding/emailBox")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.deleteEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
            });
        }).rejects.toThrow(Namecom.InternalServerError);
    });

    test("DeleteEmailForwarding (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/core/v1/domains/domainName/email/forwarding/emailBox")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.deleteEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
            });
        }).rejects.toThrow(Namecom.BadGatewayError);
    });

    test("DeleteEmailForwarding (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/core/v1/domains/domainName/email/forwarding/emailBox")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.deleteEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
            });
        }).rejects.toThrow(Namecom.ServiceUnavailableError);
    });

    test("DeleteEmailForwarding (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/core/v1/domains/domainName/email/forwarding/emailBox")
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.emailForwardings.deleteEmailForwarding({
                domainName: "domainName",
                emailBox: "emailBox",
            });
        }).rejects.toThrow(Namecom.GatewayTimeoutError);
    });
});
