// This file was auto-generated by Fern from our API Definition.

import * as Namecom from "../../src/api/index";
import { NamecomClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("NamecomClient", () => {
    test("Hello (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            motd: "motd",
            serverName: "serverName",
            serverTime: "serverTime",
            username: "username",
        };

        server.mockEndpoint().get("/core/v1/hello").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.hello();
        expect(response).toEqual(rawResponseBody);
    });

    test("Hello (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/core/v1/hello").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.hello();
        }).rejects.toThrow(Namecom.UnauthorizedError);
    });

    test("Hello (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/core/v1/hello").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.hello();
        }).rejects.toThrow(Namecom.ForbiddenError);
    });

    test("Hello (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/core/v1/hello").respondWith().statusCode(405).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.hello();
        }).rejects.toThrow(Namecom.MethodNotAllowedError);
    });

    test("Hello (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/core/v1/hello").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.hello();
        }).rejects.toThrow(Namecom.TooManyRequestsError);
    });

    test("Hello (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/core/v1/hello").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.hello();
        }).rejects.toThrow(Namecom.InternalServerError);
    });

    test("Hello (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/core/v1/hello").respondWith().statusCode(502).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.hello();
        }).rejects.toThrow(Namecom.BadGatewayError);
    });

    test("Hello (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/core/v1/hello").respondWith().statusCode(504).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.hello();
        }).rejects.toThrow(Namecom.GatewayTimeoutError);
    });
});
