// This file was auto-generated by Fern from our API Definition.

import * as Namecom from "../../src/api/index";
import { NamecomClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("RefundsClient", () => {
    test("ProcessRefund (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { orderId: 123456, orderItemIds: [987654] };
        const rawResponseBody = {
            results: [
                {
                    orderId: 123456,
                    orderItemId: 987654,
                    orderItemStatus: "refunded",
                    refundAmount: 10.99,
                    message: "Domain successfully deleted and refund processed.",
                },
            ],
            totalRefundAmount: 10.99,
        };

        server
            .mockEndpoint()
            .post("/core/v1/refund")
            .header("X-Idempotency-Key", "083910ef-04e4-4bd1-a0bf-3737fe005ca8")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.refunds.processRefund({
            "X-Idempotency-Key": "083910ef-04e4-4bd1-a0bf-3737fe005ca8",
            orderId: 123456,
            orderItemIds: [987654],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("ProcessRefund (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { orderId: 123456, orderItemIds: [987654, 987655] };
        const rawResponseBody = {
            results: [
                {
                    orderId: 123456,
                    orderItemId: 987654,
                    orderItemStatus: "refunded",
                    refundAmount: 10.99,
                    message: "Domain successfully deleted and refund processed.",
                },
            ],
            totalRefundAmount: 10.99,
        };

        server
            .mockEndpoint()
            .post("/core/v1/refund")
            .header("X-Idempotency-Key", "083910ef-04e4-4bd1-a0bf-3737fe005ca8")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.refunds.processRefund({
            "X-Idempotency-Key": "083910ef-04e4-4bd1-a0bf-3737fe005ca8",
            orderId: 123456,
            orderItemIds: [987654, 987655],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("ProcessRefund (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { orderId: 1, orderItemIds: [1, 1] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/refund")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.refunds.processRefund({
                orderId: 1,
                orderItemIds: [1, 1],
            });
        }).rejects.toThrow(Namecom.BadRequestError);
    });

    test("ProcessRefund (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { orderId: 1, orderItemIds: [1, 1] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/refund")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.refunds.processRefund({
                orderId: 1,
                orderItemIds: [1, 1],
            });
        }).rejects.toThrow(Namecom.UnauthorizedError);
    });

    test("ProcessRefund (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { orderId: 1, orderItemIds: [1, 1] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/refund")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.refunds.processRefund({
                orderId: 1,
                orderItemIds: [1, 1],
            });
        }).rejects.toThrow(Namecom.ForbiddenError);
    });

    test("ProcessRefund (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { orderId: 1, orderItemIds: [1, 1] };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/core/v1/refund")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.refunds.processRefund({
                orderId: 1,
                orderItemIds: [1, 1],
            });
        }).rejects.toThrow(Namecom.NotFoundError);
    });

    test("ProcessRefund (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { orderId: 1, orderItemIds: [1, 1] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/refund")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.refunds.processRefund({
                orderId: 1,
                orderItemIds: [1, 1],
            });
        }).rejects.toThrow(Namecom.MethodNotAllowedError);
    });

    test("ProcessRefund (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { orderId: 1, orderItemIds: [1, 1] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/refund")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.refunds.processRefund({
                orderId: 1,
                orderItemIds: [1, 1],
            });
        }).rejects.toThrow(Namecom.ConflictError);
    });

    test("ProcessRefund (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { orderId: 1, orderItemIds: [1, 1] };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/core/v1/refund")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(415)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.refunds.processRefund({
                orderId: 1,
                orderItemIds: [1, 1],
            });
        }).rejects.toThrow(Namecom.UnsupportedMediaTypeError);
    });

    test("ProcessRefund (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { orderId: 1, orderItemIds: [1, 1] };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/core/v1/refund")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(423)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.refunds.processRefund({
                orderId: 1,
                orderItemIds: [1, 1],
            });
        }).rejects.toThrow(Namecom.LockedError);
    });

    test("ProcessRefund (11)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { orderId: 1, orderItemIds: [1, 1] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/refund")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.refunds.processRefund({
                orderId: 1,
                orderItemIds: [1, 1],
            });
        }).rejects.toThrow(Namecom.TooManyRequestsError);
    });

    test("ProcessRefund (12)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { orderId: 1, orderItemIds: [1, 1] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/refund")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.refunds.processRefund({
                orderId: 1,
                orderItemIds: [1, 1],
            });
        }).rejects.toThrow(Namecom.InternalServerError);
    });

    test("ProcessRefund (13)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { orderId: 1, orderItemIds: [1, 1] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/refund")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.refunds.processRefund({
                orderId: 1,
                orderItemIds: [1, 1],
            });
        }).rejects.toThrow(Namecom.BadGatewayError);
    });

    test("ProcessRefund (14)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { orderId: 1, orderItemIds: [1, 1] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/refund")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.refunds.processRefund({
                orderId: 1,
                orderItemIds: [1, 1],
            });
        }).rejects.toThrow(Namecom.GatewayTimeoutError);
    });
});
