// This file was auto-generated by Fern from our API Definition.

import * as Namecom from "../../src/api/index";
import { NamecomClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("TransfersClient", () => {
    test("ListTransfers (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            lastPage: 1,
            nextPage: 1,
            totalCount: 1,
            from: 1,
            to: 1,
            transfers: [{ domainName: "example.com", email: "admin@example.com", status: "canceled" }],
        };

        server.mockEndpoint().get("/core/v1/transfers").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.transfers.listTransfers();
        expect(response).toEqual(rawResponseBody);
    });

    test("ListTransfers (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/core/v1/transfers").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.transfers.listTransfers();
        }).rejects.toThrow(Namecom.BadRequestError);
    });

    test("ListTransfers (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/core/v1/transfers").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.transfers.listTransfers();
        }).rejects.toThrow(Namecom.UnauthorizedError);
    });

    test("ListTransfers (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/core/v1/transfers").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.transfers.listTransfers();
        }).rejects.toThrow(Namecom.PaymentRequiredError);
    });

    test("ListTransfers (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/core/v1/transfers").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.transfers.listTransfers();
        }).rejects.toThrow(Namecom.ForbiddenError);
    });

    test("ListTransfers (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/core/v1/transfers").respondWith().statusCode(405).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.transfers.listTransfers();
        }).rejects.toThrow(Namecom.MethodNotAllowedError);
    });

    test("ListTransfers (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/core/v1/transfers").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.transfers.listTransfers();
        }).rejects.toThrow(Namecom.TooManyRequestsError);
    });

    test("ListTransfers (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/core/v1/transfers").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.transfers.listTransfers();
        }).rejects.toThrow(Namecom.InternalServerError);
    });

    test("ListTransfers (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/core/v1/transfers").respondWith().statusCode(502).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.transfers.listTransfers();
        }).rejects.toThrow(Namecom.BadGatewayError);
    });

    test("ListTransfers (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/core/v1/transfers").respondWith().statusCode(504).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.transfers.listTransfers();
        }).rejects.toThrow(Namecom.GatewayTimeoutError);
    });

    test("CreateTransfer (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { authCode: "ABC123", domainName: "example.com" };
        const rawResponseBody = {
            order: 12345,
            totalPaid: 12.99,
            transfer: { domainName: "example.com", email: "admin@example.com", status: "canceled" },
            warnings: {
                message:
                    "Domain has registry statuses that may prevent a successful transfer. Please ensure the domain is unlocked and eligible at the losing registrar.",
                statuses: ["clientTransferProhibited", "clientUpdateProhibited"],
            },
        };

        server
            .mockEndpoint()
            .post("/core/v1/transfers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.transfers.createTransfer({
            authCode: "ABC123",
            domainName: "example.com",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("CreateTransfer (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { authCode: "x", domainName: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.createTransfer({
                authCode: "x",
                domainName: "x",
            });
        }).rejects.toThrow(Namecom.BadRequestError);
    });

    test("CreateTransfer (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { authCode: "x", domainName: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.createTransfer({
                authCode: "x",
                domainName: "x",
            });
        }).rejects.toThrow(Namecom.UnauthorizedError);
    });

    test("CreateTransfer (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { authCode: "x", domainName: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.createTransfer({
                authCode: "x",
                domainName: "x",
            });
        }).rejects.toThrow(Namecom.PaymentRequiredError);
    });

    test("CreateTransfer (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { authCode: "x", domainName: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.createTransfer({
                authCode: "x",
                domainName: "x",
            });
        }).rejects.toThrow(Namecom.ForbiddenError);
    });

    test("CreateTransfer (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { authCode: "x", domainName: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.createTransfer({
                authCode: "x",
                domainName: "x",
            });
        }).rejects.toThrow(Namecom.MethodNotAllowedError);
    });

    test("CreateTransfer (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { authCode: "x", domainName: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.createTransfer({
                authCode: "x",
                domainName: "x",
            });
        }).rejects.toThrow(Namecom.ConflictError);
    });

    test("CreateTransfer (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { authCode: "x", domainName: "x" };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(415)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.createTransfer({
                authCode: "x",
                domainName: "x",
            });
        }).rejects.toThrow(Namecom.UnsupportedMediaTypeError);
    });

    test("CreateTransfer (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { authCode: "x", domainName: "x" };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.createTransfer({
                authCode: "x",
                domainName: "x",
            });
        }).rejects.toThrow(Namecom.UnprocessableEntityError);
    });

    test("CreateTransfer (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { authCode: "x", domainName: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.createTransfer({
                authCode: "x",
                domainName: "x",
            });
        }).rejects.toThrow(Namecom.TooManyRequestsError);
    });

    test("CreateTransfer (11)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { authCode: "x", domainName: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.createTransfer({
                authCode: "x",
                domainName: "x",
            });
        }).rejects.toThrow(Namecom.InternalServerError);
    });

    test("CreateTransfer (12)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { authCode: "x", domainName: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.createTransfer({
                authCode: "x",
                domainName: "x",
            });
        }).rejects.toThrow(Namecom.BadGatewayError);
    });

    test("CreateTransfer (13)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { authCode: "x", domainName: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.createTransfer({
                authCode: "x",
                domainName: "x",
            });
        }).rejects.toThrow(Namecom.GatewayTimeoutError);
    });

    test("GetTransfer (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { domainName: "example.com", email: "admin@example.com", status: "canceled" };

        server
            .mockEndpoint()
            .get("/core/v1/transfers/domainName")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.transfers.getTransfer({
            domainName: "domainName",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("GetTransfer (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/transfers/domainName")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.getTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.UnauthorizedError);
    });

    test("GetTransfer (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/transfers/domainName")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.getTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.ForbiddenError);
    });

    test("GetTransfer (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .get("/core/v1/transfers/domainName")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.getTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.NotFoundError);
    });

    test("GetTransfer (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/transfers/domainName")
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.getTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.MethodNotAllowedError);
    });

    test("GetTransfer (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .get("/core/v1/transfers/domainName")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.getTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.UnprocessableEntityError);
    });

    test("GetTransfer (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/transfers/domainName")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.getTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.TooManyRequestsError);
    });

    test("GetTransfer (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/transfers/domainName")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.getTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.InternalServerError);
    });

    test("GetTransfer (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/transfers/domainName")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.getTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.BadGatewayError);
    });

    test("GetTransfer (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/transfers/domainName")
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.getTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.GatewayTimeoutError);
    });

    test("CancelTransfer (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { domainName: "example.com", email: "admin@example.com", status: "canceled" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/domainName:cancel")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.transfers.cancelTransfer({
            domainName: "domainName",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("CancelTransfer (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/domainName:cancel")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.cancelTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.BadRequestError);
    });

    test("CancelTransfer (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/domainName:cancel")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.cancelTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.UnauthorizedError);
    });

    test("CancelTransfer (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/domainName:cancel")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.cancelTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.ForbiddenError);
    });

    test("CancelTransfer (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/domainName:cancel")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.cancelTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.NotFoundError);
    });

    test("CancelTransfer (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/domainName:cancel")
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.cancelTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.MethodNotAllowedError);
    });

    test("CancelTransfer (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/domainName:cancel")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.cancelTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.ConflictError);
    });

    test("CancelTransfer (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/domainName:cancel")
            .respondWith()
            .statusCode(415)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.cancelTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.UnsupportedMediaTypeError);
    });

    test("CancelTransfer (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/domainName:cancel")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.cancelTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.TooManyRequestsError);
    });

    test("CancelTransfer (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/domainName:cancel")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.cancelTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.InternalServerError);
    });

    test("CancelTransfer (11)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/domainName:cancel")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.cancelTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.BadGatewayError);
    });

    test("CancelTransfer (12)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/domainName:cancel")
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.cancelTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.GatewayTimeoutError);
    });

    test("CancelOutboundTransfer (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { domainName: "example.com", status: "canceled" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/external/out/example.com:cancel")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.transfers.cancelOutboundTransfer({
            domainName: "example.com",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("CancelOutboundTransfer (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/external/out/domainName:cancel")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.cancelOutboundTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.UnauthorizedError);
    });

    test("CancelOutboundTransfer (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/external/out/domainName:cancel")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.cancelOutboundTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.ForbiddenError);
    });

    test("CancelOutboundTransfer (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/external/out/domainName:cancel")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.cancelOutboundTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.NotFoundError);
    });

    test("CancelOutboundTransfer (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/external/out/domainName:cancel")
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.cancelOutboundTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.MethodNotAllowedError);
    });

    test("CancelOutboundTransfer (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/external/out/domainName:cancel")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.cancelOutboundTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.ConflictError);
    });

    test("CancelOutboundTransfer (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/external/out/domainName:cancel")
            .respondWith()
            .statusCode(415)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.cancelOutboundTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.UnsupportedMediaTypeError);
    });

    test("CancelOutboundTransfer (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/external/out/domainName:cancel")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.cancelOutboundTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.UnprocessableEntityError);
    });

    test("CancelOutboundTransfer (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/external/out/domainName:cancel")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.cancelOutboundTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.TooManyRequestsError);
    });

    test("CancelOutboundTransfer (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/external/out/domainName:cancel")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.cancelOutboundTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.InternalServerError);
    });

    test("CancelOutboundTransfer (11)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/external/out/domainName:cancel")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.cancelOutboundTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.BadGatewayError);
    });

    test("CancelOutboundTransfer (12)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/external/out/domainName:cancel")
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.cancelOutboundTransfer({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.GatewayTimeoutError);
    });

    test("CreateInternalTransferIn (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { domainName: "example.com", authCode: "ABC123" };
        const rawResponseBody = {
            domainName: "example.com",
            createDate: "2023-01-15T14:30:00Z",
            expireDate: "2025-01-15T14:30:00Z",
            autorenewEnabled: true,
            locked: true,
            locks: ["clientTransferProhibited", "clientHold"],
            transferLockExpiresAt: "2023-03-16T14:30:00Z",
            privacyEnabled: true,
            contacts: {
                admin: {
                    firstName: "John",
                    lastName: "Doe",
                    companyName: "Example Inc.",
                    address1: "123 Main Street",
                    address2: "Suite 400",
                    city: "New York",
                    state: "NY",
                    zip: "10001",
                    country: "US",
                    email: "john.doe@example.com",
                    phone: "+15551234567",
                    fax: "+15557654321",
                    isVerified: true,
                    verificationId: 12345,
                },
                billing: {
                    firstName: "John",
                    lastName: "Doe",
                    companyName: "Example Inc.",
                    address1: "123 Main Street",
                    address2: "Suite 400",
                    city: "New York",
                    state: "NY",
                    zip: "10001",
                    country: "US",
                    email: "john.doe@example.com",
                    phone: "+15551234567",
                    fax: "+15557654321",
                    isVerified: true,
                    verificationId: 12345,
                },
                registrant: {
                    firstName: "John",
                    lastName: "Doe",
                    companyName: "Example Inc.",
                    address1: "123 Main Street",
                    address2: "Suite 400",
                    city: "New York",
                    state: "NY",
                    zip: "10001",
                    country: "US",
                    email: "john.doe@example.com",
                    phone: "+15551234567",
                    fax: "+15557654321",
                    isVerified: true,
                    verificationId: 12345,
                },
                tech: {
                    firstName: "John",
                    lastName: "Doe",
                    companyName: "Example Inc.",
                    address1: "123 Main Street",
                    address2: "Suite 400",
                    city: "New York",
                    state: "NY",
                    zip: "10001",
                    country: "US",
                    email: "john.doe@example.com",
                    phone: "+15551234567",
                    fax: "+15557654321",
                    isVerified: true,
                    verificationId: 12345,
                },
            },
            nameservers: ["ns1.example.com", "ns2.example.com"],
            renewalPrice: 12.99,
        };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/internal/in")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.transfers.createInternalTransferIn({
            domainName: "example.com",
            authCode: "ABC123",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("CreateInternalTransferIn (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { domainName: "x", authCode: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/internal/in")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.createInternalTransferIn({
                domainName: "x",
                authCode: "x",
            });
        }).rejects.toThrow(Namecom.BadRequestError);
    });

    test("CreateInternalTransferIn (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { domainName: "x", authCode: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/internal/in")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.createInternalTransferIn({
                domainName: "x",
                authCode: "x",
            });
        }).rejects.toThrow(Namecom.UnauthorizedError);
    });

    test("CreateInternalTransferIn (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { domainName: "x", authCode: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/internal/in")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.createInternalTransferIn({
                domainName: "x",
                authCode: "x",
            });
        }).rejects.toThrow(Namecom.ForbiddenError);
    });

    test("CreateInternalTransferIn (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { domainName: "x", authCode: "x" };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/internal/in")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.createInternalTransferIn({
                domainName: "x",
                authCode: "x",
            });
        }).rejects.toThrow(Namecom.NotFoundError);
    });

    test("CreateInternalTransferIn (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { domainName: "x", authCode: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/internal/in")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.createInternalTransferIn({
                domainName: "x",
                authCode: "x",
            });
        }).rejects.toThrow(Namecom.MethodNotAllowedError);
    });

    test("CreateInternalTransferIn (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { domainName: "x", authCode: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/internal/in")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.createInternalTransferIn({
                domainName: "x",
                authCode: "x",
            });
        }).rejects.toThrow(Namecom.ConflictError);
    });

    test("CreateInternalTransferIn (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { domainName: "x", authCode: "x" };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/internal/in")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(415)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.createInternalTransferIn({
                domainName: "x",
                authCode: "x",
            });
        }).rejects.toThrow(Namecom.UnsupportedMediaTypeError);
    });

    test("CreateInternalTransferIn (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { domainName: "x", authCode: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/internal/in")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.createInternalTransferIn({
                domainName: "x",
                authCode: "x",
            });
        }).rejects.toThrow(Namecom.TooManyRequestsError);
    });

    test("CreateInternalTransferIn (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { domainName: "x", authCode: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/internal/in")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.createInternalTransferIn({
                domainName: "x",
                authCode: "x",
            });
        }).rejects.toThrow(Namecom.InternalServerError);
    });

    test("CreateInternalTransferIn (11)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { domainName: "x", authCode: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/internal/in")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.createInternalTransferIn({
                domainName: "x",
                authCode: "x",
            });
        }).rejects.toThrow(Namecom.BadGatewayError);
    });

    test("CreateInternalTransferIn (12)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { domainName: "x", authCode: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/core/v1/transfers/internal/in")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.createInternalTransferIn({
                domainName: "x",
                authCode: "x",
            });
        }).rejects.toThrow(Namecom.GatewayTimeoutError);
    });

    test("GetTransferEligibility (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { domainName: "example.com", atName: true, supportsInternalTransfer: true };

        server
            .mockEndpoint()
            .get("/core/v1/transfers/eligibility/domainName")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.transfers.getTransferEligibility({
            domainName: "domainName",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("GetTransferEligibility (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { domainName: "example.com", atName: false, supportsInternalTransfer: true };

        server
            .mockEndpoint()
            .get("/core/v1/transfers/eligibility/domainName")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.transfers.getTransferEligibility({
            domainName: "domainName",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("GetTransferEligibility (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/transfers/eligibility/domainName")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.getTransferEligibility({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.BadRequestError);
    });

    test("GetTransferEligibility (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/transfers/eligibility/domainName")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.getTransferEligibility({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.UnauthorizedError);
    });

    test("GetTransferEligibility (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/transfers/eligibility/domainName")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.getTransferEligibility({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.ForbiddenError);
    });

    test("GetTransferEligibility (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/transfers/eligibility/domainName")
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.getTransferEligibility({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.MethodNotAllowedError);
    });

    test("GetTransferEligibility (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .get("/core/v1/transfers/eligibility/domainName")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.getTransferEligibility({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.UnprocessableEntityError);
    });

    test("GetTransferEligibility (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/transfers/eligibility/domainName")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.getTransferEligibility({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.TooManyRequestsError);
    });

    test("GetTransferEligibility (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/transfers/eligibility/domainName")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.getTransferEligibility({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.InternalServerError);
    });

    test("GetTransferEligibility (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/transfers/eligibility/domainName")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.getTransferEligibility({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.BadGatewayError);
    });

    test("GetTransferEligibility (11)", async () => {
        const server = mockServerPool.createServer();
        const client = new NamecomClient({
            maxRetries: 0,
            username: "test",
            password: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/core/v1/transfers/eligibility/domainName")
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transfers.getTransferEligibility({
                domainName: "domainName",
            });
        }).rejects.toThrow(Namecom.GatewayTimeoutError);
    });
});
