// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         domainName: "domainName"
 *     }
 */
export interface DomainsPurchasePrivacyBody {
    /** DomainName is the domain to enable or extend Whois Privacy for. */
    domainName: string;
    /** WHOIS privacy is free for API users. This field does not add a privacy fee. */
    purchasePrice?: number;
    /** Years is the number of years to enable or extend Whois Privacy for. Years defaults to 1 and cannot be more then the domain expiration date. */
    years?: number;
}
