// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         domainName: "example.com"
 *     }
 */
export interface EnableAutorenewRequest {
    /** DomainName is the domain name to enable autorenew for. */
    domainName: string;
}
