// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../../../../index.js";

/**
 * @example
 *     {
 *         domainName: "example.com",
 *         body: {}
 *     }
 */
export interface EnableAutorenewRequest {
    /** DomainName is the domain name to enable autorenew for. */
    domainName: string;
    body: Namecom.EmptyObject;
}
