// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../../../../index.js";

/**
 * @example
 *     {
 *         domainName: "domainName",
 *         body: {}
 *     }
 */
export interface EnableWhoisPrivacyRequest {
    /** DomainName is the domain name to enable whoisprivacy for. */
    domainName: string;
    body: Namecom.EmptyObject;
}
