// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         domainName: "domainName"
 *     }
 */
export interface GetAuthCodeForDomainRequest {
    /** DomainName is the domain name to retrieve the authorization code for. */
    domainName: string;
}
