// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         domainName: "example.com"
 *     }
 */
export interface GetDomainRequest {
    /** DomainName is the domain to retrieve. */
    domainName: string;
}
