// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         domainName: "domainName",
 *         years: 2
 *     }
 */
export interface GetPricingForDomainRequest {
    /** DomainName is the domain to retrieve. */
    domainName: string;
    /** Years specifies the registration term to price in years. Defaults to each TLD's minimum registration term if omitted — usually 1 year (2 for `.ai`). Must be a supported registration term for the TLD (commonly 1–10 years). Use the same value on Create Domain when passing `purchasePrice` for `purchaseType: registration`. */
    years?: number;
}
