// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         domainName: "domainName"
 *     }
 */
export interface UpdateDomainRequest {
    /** DomainName is the domain to update. */
    domainName: string;
    /** Enable or disable automatic renewal for the domain. */
    autorenewEnabled?: boolean;
    /** Enable or disable Whois privacy for the domain. */
    privacyEnabled?: boolean;
    /** Set the transfer lock status for the domain */
    locked?: boolean;
}
