// This file was auto-generated by Fern from our API Definition.

import * as Namecom from "./api/index.js";
import { AccountInfoClient } from "./api/resources/accountInfo/client/Client.js";
import { AccountsClient } from "./api/resources/accounts/client/Client.js";
import { ContactVerificationClient } from "./api/resources/contactVerification/client/Client.js";
import { DnsClient } from "./api/resources/dns/client/Client.js";
import { DnsseCsClient } from "./api/resources/dnsseCs/client/Client.js";
import { DomainInfoClient } from "./api/resources/domainInfo/client/Client.js";
import { DomainsClient } from "./api/resources/domains/client/Client.js";
import { EmailForwardingsClient } from "./api/resources/emailForwardings/client/Client.js";
import { OrdersClient } from "./api/resources/orders/client/Client.js";
import { PremiumDomainsClient } from "./api/resources/premiumDomains/client/Client.js";
import { RefundsClient } from "./api/resources/refunds/client/Client.js";
import { TldPricingClient } from "./api/resources/tldPricing/client/Client.js";
import { TransfersClient } from "./api/resources/transfers/client/Client.js";
import { UrlForwardingsClient } from "./api/resources/urlForwardings/client/Client.js";
import { VanityNameserversClient } from "./api/resources/vanityNameservers/client/Client.js";
import { WebhookNotificationsClient } from "./api/resources/webhookNotifications/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import { mergeHeaders } from "./core/headers.js";
import * as core from "./core/index.js";
import * as environments from "./environments.js";
import { handleNonStatusCodeError } from "./errors/handleNonStatusCodeError.js";
import * as errors from "./errors/index.js";

export declare namespace NamecomClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class NamecomClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<NamecomClient.Options>;
    protected _accountInfo: AccountInfoClient | undefined;
    protected _accounts: AccountsClient | undefined;
    protected _domains: DomainsClient | undefined;
    protected _dnsseCs: DnsseCsClient | undefined;
    protected _emailForwardings: EmailForwardingsClient | undefined;
    protected _dns: DnsClient | undefined;
    protected _urlForwardings: UrlForwardingsClient | undefined;
    protected _vanityNameservers: VanityNameserversClient | undefined;
    protected _webhookNotifications: WebhookNotificationsClient | undefined;
    protected _orders: OrdersClient | undefined;
    protected _refunds: RefundsClient | undefined;
    protected _transfers: TransfersClient | undefined;
    protected _domainInfo: DomainInfoClient | undefined;
    protected _tldPricing: TldPricingClient | undefined;
    protected _premiumDomains: PremiumDomainsClient | undefined;
    protected _contactVerification: ContactVerificationClient | undefined;

    constructor(options: NamecomClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get accountInfo(): AccountInfoClient {
        return (this._accountInfo ??= new AccountInfoClient(this._options));
    }

    public get accounts(): AccountsClient {
        return (this._accounts ??= new AccountsClient(this._options));
    }

    public get domains(): DomainsClient {
        return (this._domains ??= new DomainsClient(this._options));
    }

    public get dnsseCs(): DnsseCsClient {
        return (this._dnsseCs ??= new DnsseCsClient(this._options));
    }

    public get emailForwardings(): EmailForwardingsClient {
        return (this._emailForwardings ??= new EmailForwardingsClient(this._options));
    }

    public get dns(): DnsClient {
        return (this._dns ??= new DnsClient(this._options));
    }

    public get urlForwardings(): UrlForwardingsClient {
        return (this._urlForwardings ??= new UrlForwardingsClient(this._options));
    }

    public get vanityNameservers(): VanityNameserversClient {
        return (this._vanityNameservers ??= new VanityNameserversClient(this._options));
    }

    public get webhookNotifications(): WebhookNotificationsClient {
        return (this._webhookNotifications ??= new WebhookNotificationsClient(this._options));
    }

    public get orders(): OrdersClient {
        return (this._orders ??= new OrdersClient(this._options));
    }

    public get refunds(): RefundsClient {
        return (this._refunds ??= new RefundsClient(this._options));
    }

    public get transfers(): TransfersClient {
        return (this._transfers ??= new TransfersClient(this._options));
    }

    public get domainInfo(): DomainInfoClient {
        return (this._domainInfo ??= new DomainInfoClient(this._options));
    }

    public get tldPricing(): TldPricingClient {
        return (this._tldPricing ??= new TldPricingClient(this._options));
    }

    public get premiumDomains(): PremiumDomainsClient {
        return (this._premiumDomains ??= new PremiumDomainsClient(this._options));
    }

    public get contactVerification(): ContactVerificationClient {
        return (this._contactVerification ??= new ContactVerificationClient(this._options));
    }

    /**
     * Returns basic information about the API server (useful for testing connectivity and version checks).
     *
     * @param {NamecomClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Namecom.UnauthorizedError}
     * @throws {@link Namecom.ForbiddenError}
     * @throws {@link Namecom.MethodNotAllowedError}
     * @throws {@link Namecom.TooManyRequestsError}
     * @throws {@link Namecom.InternalServerError}
     * @throws {@link Namecom.BadGatewayError}
     * @throws {@link Namecom.ServiceUnavailableError}
     * @throws {@link Namecom.GatewayTimeoutError}
     *
     * @example
     *     await client.hello()
     */
    public hello(requestOptions?: NamecomClient.RequestOptions): core.HttpResponsePromise<Namecom.HelloResponse> {
        return core.HttpResponsePromise.fromPromise(this.__hello(requestOptions));
    }

    private async __hello(
        requestOptions?: NamecomClient.RequestOptions,
    ): Promise<core.WithRawResponse<Namecom.HelloResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NamecomEnvironment.Sandbox,
                "core/v1/hello",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Namecom.HelloResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Namecom.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Namecom.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 405:
                    throw new Namecom.MethodNotAllowedError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Namecom.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Namecom.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 502:
                    throw new Namecom.BadGatewayError(_response.error.body as unknown, _response.rawResponse);
                case 503:
                    throw new Namecom.ServiceUnavailableError(_response.error.body as unknown, _response.rawResponse);
                case 504:
                    throw new Namecom.GatewayTimeoutError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.NamecomError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/core/v1/hello");
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
