// This file was auto-generated by Fern from our API Definition.

export const NamecomEnvironment = {
    Sandbox: "https://api.dev.name.com",
    Production: "https://api.name.com",
} as const;

export type NamecomEnvironment = typeof NamecomEnvironment.Sandbox | typeof NamecomEnvironment.Production;
