// This file was auto-generated by Fern from our API Definition.

export const NamecomEnvironment = {
    Default: "https://api.dev.name.com",
} as const;

export type NamecomEnvironment = typeof NamecomEnvironment.Default;
