// This file was auto-generated by Fern from our API Definition.

import type * as Namecom from "../../../../index.js";

/**
 * @example
 *     {
 *         verificationId: 1,
 *         body: {}
 *     }
 */
export interface ResendContactVerificationEmailRequest {
    /** The verificationId for the pending contact verification record. */
    verificationId: number;
    body: Namecom.EmptyObject;
}
