// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         perPage: 100,
 *         page: 2
 *     }
 */
export interface UnverifiedContactsListRequest {
    /** PerPage is the number of records to return per request. If not passed in the request, the default value is 100 records. */
    perPage?: number;
    /** Page is which page to return. If not passed in the request, the default page is 1. */
    page?: number;
}
