// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "X-Idempotency-Key": "083910ef-04e4-4bd1-a0bf-3737fe005ca8",
 *         verificationId: 1
 *     }
 */
export interface VerifyContactRequest {
    /** The VerificationId required to verify a specific contact. */
    verificationId: number;
    /** A unique string (e.g., a UUID v4) to make the request idempotent. This key ensures that if the request is retried, the operation will not be performed multiple times. Subsequent requests with the same key will return the original result. */
    "X-Idempotency-Key"?: string;
}
